#!/usr/bin/env python3
"""
generate_rpc.py — Generate Rust RPC code from rpc_protocol.toml

Produces:
  - rpc_common_generated.rs  (constants)
  - rpc_target_generated.rs  (target-side dispatch)
  - rpc_host_generated.rs    (host-side client callers)

Usage:
  python3 generate_rpc.py rpc_protocol.toml --out-dir src/
"""

import argparse
import os
import sys
from pathlib import Path

try:
    import tomllib
except ImportError:
    try:
        import tomli as tomllib
    except ImportError:
        print("ERROR: need tomllib (Python 3.11+) or tomli", file=sys.stderr)
        sys.exit(1)


# ---------------------------------------------------------------------------
# Type → hex digit count + encoder/decoder helpers
# ---------------------------------------------------------------------------

TYPE_INFO = {
    "u8":       {"digits": 2,  "enc": "add_u32_no_padding", "dec": "next_u8"},
    "u16":      {"digits": 4,  "enc": "add_u32_le",         "dec": "next_u16"},
    "u16_be":   {"digits": 4,  "enc": "add_u32",            "dec": "next_u16_be"},
    "u32":      {"digits": 8,  "enc": "add_u32_le",         "dec": "next_u32"},
    "u32_le":   {"digits": 8,  "enc": "add_u32_le",         "dec": "next_u32"},
    "u32_be":   {"digits": 8,  "enc": "add_u32",            "dec": "next_u32_be"},
    "bool":     {"digits": 1,  "enc": "add_u8",             "dec": "next_bool"},
}

# Reverse mapping: class id byte → class name
CLASS_ID_TO_NAME = {}


def load_spec(path):
    """Load and validate the TOML spec."""
    with open(path, "rb") as f:
        data = tomllib.load(f)

    # TOML dotted keys like [class.GEN] create nested dicts:
    # data["class"]["GEN"]["command"]["START"] etc.
    classes_data = data.get("class", {})
    classes = []
    for class_name, class_val in classes_data.items():
        class_id = class_val["id"]
        handler = class_val.get("handler", f"rpc_{class_name.lower()}_impl")
        description = class_val.get("description", "")

        commands_data = class_val.get("command", {})
        commands = []
        for cmd_name, cmd_val in commands_data.items():
            cmd_id = cmd_val["id"]
            cmd_desc = cmd_val.get("description", "")
            params = cmd_val.get("params", [])
            reply = cmd_val.get("reply", "ok")

            old_name = cmd_val.get("old_name", None)
            commands.append({
                "name": cmd_name,
                "id": cmd_id,
                "description": cmd_desc,
                "params": params,
                "reply": reply,
                "old_name": old_name,
            })

        classes.append({
            "name": class_name,
            "id": class_id,
            "handler": handler,
            "description": description,
            "commands": commands,
        })
        CLASS_ID_TO_NAME[class_id] = class_name

    return classes


def const_name(class_name, cmd_name=None):
    """Generate the constant name for a class or command."""
    if cmd_name:
        return f"RPC_{class_name}_{cmd_name}"
    return f"RPC_{class_name}_PACKET"


def rust_byte_literal(c):
    """Convert a single ASCII character to a Rust byte literal."""
    if c.isascii() and c.isprintable() and c not in "'\\":
        return f"b'{c}'"
    return f"{ord(c)}u8"


# ---------------------------------------------------------------------------
# Generator: rpc_common_generated.rs
# ---------------------------------------------------------------------------

def gen_common(classes):
    lines = [
        "// Auto-generated by generate_rpc.py — DO NOT EDIT",
        "// Source: rpc_protocol.toml",
        "",
        "#![allow(dead_code)]",
        "#![allow(non_upper_case_globals)]",
        "#![allow(unused_variables)]",
        "#![allow(unused_imports)]",
        "",
        "// ── Packet class bytes ──",
    ]
    for cls in classes:
        cname = const_name(cls['name'])
        lines.append(f"pub const {cname}: u8 = {rust_byte_literal(cls['id'])};")

    lines += ["", "// ── Command bytes ──"]
    for cls in classes:
        for cmd in cls["commands"]:
            cname = const_name(cls['name'], cmd['name'])
            lines.append(f"pub const {cname}: u8 = {rust_byte_literal(cmd['id'])};")

    lines += ["", "// ── Response codes ──",
              "pub const RPC_RESP_OK: u8 = b'K';",
              "pub const RPC_RESP_PARERR: u8 = b'P';",
              "pub const RPC_RESP_ERR: u8 = b'E';",
              "pub const RPC_RESP_NOTSUP: u8 = b'N';",
              "pub const RPC_REMOTE_RESP: u8 = b'&';",
              "",
              "// ── Error codes ──",
              "pub const RPC_ERROR_UNRECOGNISED: u8 = 1;",
              "pub const RPC_ERROR_WRONGLEN: u8 = 2;",
              "pub const RPC_ERROR_FAULT: u8 = 3;",
              "pub const RPC_ERROR_EXCEPTION: u8 = 4;",
              "",
              "// ── Framing ──",
              "pub const RPC_END: u8 = b'#';",
              ]

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Generator: rpc_target_generated.rs
# ---------------------------------------------------------------------------

def gen_target(classes):
    lines = [
        "// Auto-generated by generate_rpc.py — DO NOT EDIT",
        "// Source: rpc_protocol.toml",
        "",
        "#![allow(dead_code)]",
        "#![allow(non_snake_case)]",
        "#![allow(unused_variables)]",
        "#![allow(unused_imports)]",
        "",
        "use crate::rpc_common_generated::*;",
        "use crate::rpc_target::rpc_parser::rpc_parameter_parser;",
        "use crate::rpc_target::*;",
        "use crate::rpc_target::rpc_reply::*;",
        "use crate::bmp;",
        "use crate::parsing_util;",
        "use crate::encoder::*;",
        "",
        "crate::setup_log!(false);",
        "crate::gdb_print_init!();",
        "",
        "// ── Top-level dispatch ──",
        "#[unsafe(no_mangle)]",
        "pub fn rpc_dispatch(input: &[u8]) -> bool {",
        "    if input.len() < 2 {",
        "        bmplog!(\"**short rpc\\n\");",
        "        return false;",
        "    }",
        "    let mut parser = rpc_parameter_parser::new(input);",
        "    match parser.next_cmd() {",
    ]

    for cls in classes:
        if not cls["commands"]:
            continue
        lines.append(f"        {const_name(cls['name'])} => {cls['handler']}::dispatch(&mut parser),")

    lines += [
        "        _ => {",
        "            bmplog!(\"wrong RPC header\\n\");",
        "            false",
        "        }",
        "    }",
        "}",
        "",
    ]

    # Generate per-class dispatch modules
    for cls in classes:
        if not cls["commands"]:
            continue
        lines += [f"// ── {cls['name']} dispatch ──",
                  f"pub mod {cls['handler']} {{",
                  f"    use super::*;",
                  f"",
                  f"    pub fn dispatch(parser: &mut rpc_parameter_parser) -> bool {{",
                  f"        match parser.next_cmd() {{",
                  ]

        for cmd in cls["commands"]:
            cname = const_name(cls["name"], cmd["name"])
            lines.append(f"            {cname} => cmd_{cmd['name'].lower()}(parser),")

        lines += ["            _ => {",
                   "                bmplog!(\"unknown command in {} packet\\n\", stringify!(" + cls["name"] + "));",
                   "                false",
                   "            }",
                   "        }",
                   "    }",
                   ""]

        # Generate per-command handler functions
        for cmd in cls["commands"]:
            fn_name = f"cmd_{cmd['name'].lower()}"
            lines.append(f"    fn {fn_name}(parser: &mut rpc_parameter_parser) -> bool {{")

            # Decode params
            for p in cmd["params"]:
                ptype = p["type"]
                pname = p["name"]
                if ptype == "hex_block":
                    lines.append(f"        let {pname} = parser.end();")
                elif ptype == "bool":
                    lines.append(f"        let {pname} = parser.next_cmd() != b'0';")
                else:
                    ti = TYPE_INFO[ptype]
                    lines.append(f"        let {pname} = parser.{ti['dec']}();")

            # Call impl function
            impl_fn = cmd["name"].lower()
            param_names = [p["name"] for p in cmd["params"] if p["type"] != "hex_block"]
            hex_block_params = [p["name"] for p in cmd["params"] if p["type"] == "hex_block"]

            # Build the impl call
            impl_args = ", ".join(param_names)
            if hex_block_params:
                if impl_args:
                    impl_args += ", "
                impl_args += ", ".join(hex_block_params)

            reply = cmd["reply"]
            if isinstance(reply, str):
                if reply == "ok":
                    lines.append(f"        crate::rpc_target_impl::{cls['handler']}::{impl_fn}({impl_args});")
                    lines.append("        rpc_reply_encoder::new().end();")
                    lines.append("        true")
                elif reply == "string":
                    lines.append(f"        let s = crate::rpc_target_impl::{cls['handler']}::{impl_fn}({impl_args});")
                    lines.append("        rpc_reply_string(s);")
                    lines.append("        true")
                else:
                    # Simple type reply
                    lines.append(f"        let result = crate::rpc_target_impl::{cls['handler']}::{impl_fn}({impl_args});")
                    lines.append(f"        rpc_reply32_le_ok(result);")
                    lines.append("        true")
            elif isinstance(reply, dict):
                rtype = reply.get("type", "ok")
                on_error = reply.get("on_error", None)
                if rtype == "string":
                    lines.append(f"        let s = crate::rpc_target_impl::{cls['handler']}::{impl_fn}({impl_args});")
                    lines.append("        rpc_reply_string(s);")
                    lines.append("        true")
                elif rtype == "compound":
                    # Compound reply with multiple fields
                    fields = reply.get("fields", [])
                    field_names = [f["name"] for f in fields]
                    field_types = [f["type"] for f in fields]
                    # Call impl, get tuple back
                    field_list = ", ".join(field_names)
                    lines.append(f"        let ({field_list}) = crate::rpc_target_impl::{cls['handler']}::{impl_fn}({impl_args});")
                    if on_error == "fault":
                        lines.append(f"        if {field_names[0] if 'fault' not in field_names else 'fault'} != 0 {{")
                        lines.append("            rpc_reply_error(RPC_ERROR_FAULT);")
                        lines.append("            return true;")
                        lines.append("        }")
                    lines.append("        let mut reply = rpc_reply_encoder::new();")
                    for i, f in enumerate(fields):
                        ft = f["type"]
                        if ft == "u32_le":
                            lines.append(f"        reply.add_u32_le_wrapped({field_names[i]});")
                        elif ft == "u8":
                            lines.append(f"        reply.add_u8_wrapped({field_names[i]} as u8);")
                        else:
                            lines.append(f"        reply.add_u32_le_wrapped({field_names[i]});")
                    lines.append("        reply.end();")
                    lines.append("        true")
                elif rtype == "hex_block":
                    max_len = reply.get("max_length", 1024)
                    lines.append(f"        let buffer = crate::rpc_target::rpc_reply::get_temp_buffer();")
                    # Add buffer param to impl args
                    buffer_impl_args = impl_args
                    if buffer_impl_args:
                        buffer_impl_args += ", "
                    buffer_impl_args += "buffer"
                    lines.append(f"        let (fault, len) = crate::rpc_target_impl::{cls['handler']}::{impl_fn}({buffer_impl_args});")
                    if on_error == "fault":
                        lines.append("        if fault != 0 {")
                        lines.append("            rpc_reply_error(fault as u8);")
                        lines.append("            return true;")
                        lines.append("        }")
                    lines.append(f"        rpc_reply_hex_string(RPC_RESP_OK, &buffer[..len]);")
                    lines.append("        true")
                elif rtype == "u8":
                    lines.append(f"        let val = crate::rpc_target_impl::{cls['handler']}::{impl_fn}({impl_args});")
                    lines.append(f"        #[allow(clippy::unnecessary_cast)]")
                    lines.append(f"        rpc_reply_ok(val as u8);")
                    lines.append("        true")
                elif on_error == "ok_bool":
                    lines.append(f"        let (ok, value) = crate::rpc_target_impl::{cls['handler']}::{impl_fn}({impl_args});")
                    lines.append("        rpc_reply_bool_32le(ok, value);")
                    lines.append("        true")
                elif on_error == "fault":
                    lines.append(f"        let (fault, value) = crate::rpc_target_impl::{cls['handler']}::{impl_fn}({impl_args});")
                    lines.append("        reply_adiv5_32(fault, value);")
                    lines.append("        true")
                else:
                    lines.append(f"        let value = crate::rpc_target_impl::{cls['handler']}::{impl_fn}({impl_args});")
                    lines.append(f"        rpc_reply32_le_ok(value);")
                    lines.append("        true")
            lines.append("    }")
            lines.append("")

        lines.append("}\n")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Generator: rpc_host_generated.rs
# ---------------------------------------------------------------------------

def gen_host(classes):
    lines = [
        "// Auto-generated by generate_rpc.py — DO NOT EDIT",
        "// Source: rpc_protocol.toml",
        "",
        "#![allow(dead_code)]",
        "#![allow(non_snake_case)]",
        "#![allow(unused_variables)]",
        "#![allow(unused_imports)]",
        "",
        "use crate::rpc_common_generated::*;",
        "use crate::rpc_host::remote_encoder::rpc_encoder;",
        "use crate::parsing_util::{u8s_string_to_u32_le, u8s_string_to_u8};",
        "use crate::rn_bmp_cmd_c::platform_buffer_read;",
        "",
        "crate::setup_log!(false);",
        "crate::gdb_print_init!();",
        "",
        "const RPC_BUFFER_SIZE: usize = 512;",
        "static mut rpc_buffer: [u8; RPC_BUFFER_SIZE] = [0; RPC_BUFFER_SIZE];",
        "",
        "fn remote_get_reply() -> &'static [u8] {",
        "    unsafe {",
        "        let buf: *mut u8 = rpc_buffer.as_mut_ptr();",
        "        let se = platform_buffer_read(buf, RPC_BUFFER_SIZE as i32);",
        "        &rpc_buffer[0..(se as usize)]",
        "    }",
        "}",
        "",
        "fn check_reply(reply: &[u8], expected: usize) -> bool {",
        "    if reply.is_empty() { return false; }",
        "    if reply[0] != RPC_RESP_OK { return false; }",
        "    if reply.len() != (expected + 1) { return false; }",
        "    true",
        "}",
        "",
    ]

    for cls in classes:
        if not cls["commands"]:
            continue
        lines.append(f"// ── {cls['name']} commands ──")

        for cmd in cls["commands"]:
            fn_name = f"remote_{cls['name'].lower()}_{cmd['name'].lower()}"
            params = cmd["params"]
            reply = cmd["reply"]

            # Build function signature
            rust_params = []
            for p in params:
                if p["type"] == "hex_block":
                    rust_params.append(f"{p['name']}: &[u8]")
                elif p["type"] == "bool":
                    rust_params.append(f"{p['name']}: bool")
                elif p["type"] in ("u8", "u16", "u16_be"):
                    rust_params.append(f"{p['name']}: u32")
                else:
                    rust_params.append(f"{p['name']}: u32")

            # Determine return type
            if isinstance(reply, str):
                if reply == "ok":
                    ret_type = "bool"
                elif reply == "string":
                    ret_type = "&'static [u8]"
                else:
                    ret_type = "u32"
            elif isinstance(reply, dict):
                rtype = reply.get("type", "ok")
                on_error = reply.get("on_error", None)
                if rtype == "compound":
                    fields = reply.get("fields", [])
                    # Map type names to Rust types (u32_le → u32, etc.)
                    type_map = {"u32_le": "u32", "u32": "u32", "u8": "u8", "u16": "u32", "u16_be": "u32"}
                    field_types = ", ".join(type_map.get(f["type"], f["type"]) for f in fields)
                    ret_type = f"({field_types})"
                elif rtype == "hex_block":
                    ret_type = "(i32, &'static [u8])"
                elif rtype == "u8":
                    ret_type = "u8"
                elif on_error == "ok_bool":
                    ret_type = "(bool, u32)"
                elif on_error == "fault":
                    ret_type = "(i32, u32)"
                else:
                    ret_type = "u32"
            else:
                ret_type = "bool"

            lines.append(f"pub fn {fn_name}({', '.join(rust_params)}) -> {ret_type} {{")
            lines.append("    let mut e = rpc_encoder::new();")
            lines.append("    e.begin();")
            lines.append(f"    e.add_u8(&[{const_name(cls['name'])}, {const_name(cls['name'], cmd['name'])}]);")

            # Encode params
            for p in params:
                ptype = p["type"]
                pname = p["name"]
                if ptype == "hex_block":
                    lines.append(f"    // SAFETY: data is valid UTF-8 hex encoding")
                    lines.append(f"    e.hex_and_add(unsafe {{ core::str::from_utf8_unchecked({pname}) }});")
                elif ptype == "bool":
                    lines.append(f"    e.add_u8(&[if {pname} {{ b'1' }} else {{ b'0' }}]);")
                elif ptype == "u8":
                    lines.append(f"    e.add_u8_hex({pname} as u32);")
                elif ptype == "u16":
                    lines.append(f"    e.add_u16_le({pname} as u32);")
                elif ptype == "u16_be":
                    lines.append(f"    e.add_u16_be({pname} as u32);")
                elif ptype == "u32_be":
                    lines.append(f"    e.add_u32({pname} as u32);")
                else:
                    # u32, u32_le: send as 8 hex digits LE
                    lines.append(f"    e.add_u32_le({pname} as u32);")

            lines.append("    e.end();")
            lines.append("    let reply = remote_get_reply();")

            # Decode reply
            if isinstance(reply, str):
                if reply == "ok":
                    lines.append("    check_reply(reply, 0)")
                elif reply == "string":
                    lines.append("    reply")
                else:
                    lines.append(f"    if !check_reply(reply, 8) {{ return 0; }}")
                    lines.append("    u8s_string_to_u32_le(&reply[1..])")
            elif isinstance(reply, dict):
                rtype = reply.get("type", "ok")
                on_error = reply.get("on_error", None)
                if rtype == "compound":
                    fields = reply.get("fields", [])
                    expected_len = sum(TYPE_INFO[f["type"]]["digits"] for f in fields)
                    lines.append(f"    if !check_reply(reply, {expected_len}) {{")
                    if on_error == "fault":
                        lines.append("        return (1, 0);")
                    else:
                        lines.append("        return (0, 0);")
                    lines.append("    }")
                    decodes = []
                    offset = 1
                    for f in fields:
                        ft = f["type"]
                        if ft == "u32_le":
                            decodes.append(f"u8s_string_to_u32_le(&reply[{offset}..{offset + 8}])")
                            offset += 8
                        elif ft == "u8":
                            decodes.append(f"u8s_string_to_u32_le(&reply[{offset}..{offset + 2}])")
                            offset += 2
                        else:
                            decodes.append(f"u8s_string_to_u32_le(&reply[{offset}..{offset + 8}])")
                            offset += 8
                    lines.append(f"    ({', '.join(decodes)})")
                elif rtype == "hex_block":
                    lines.append("    if reply.is_empty() || reply[0] != RPC_RESP_OK {")
                    lines.append("        return (reply.get(1).copied().unwrap_or(1) as i32, &[]);")
                    lines.append("    }")
                    lines.append("    (0, &reply[1..])")
                elif rtype == "u8":
                    lines.append("    if !check_reply(reply, 2) { return 0; }")
                    lines.append("    u8s_string_to_u8(&reply[1..])")
                elif on_error == "ok_bool":
                    lines.append("    if !check_reply(reply, 8) { return (false, 0); }")
                    lines.append("    (true, u8s_string_to_u32_le(&reply[1..]))")
                elif on_error == "fault":
                    lines.append("    if reply.is_empty() || reply[0] != RPC_RESP_OK {")
                    lines.append("        return (reply.get(1).copied().unwrap_or(1) as i32, 0);")
                    lines.append("    }")
                    lines.append("    (0, u8s_string_to_u32_le(&reply[1..]))")
                else:
                    lines.append("    if !check_reply(reply, 8) { return 0; }")
                    lines.append("    u8s_string_to_u32_le(&reply[1..])")

            lines.append("}")
            lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Generate Rust RPC code from TOML spec")
    parser.add_argument("spec", help="Path to rpc_protocol.toml")
    parser.add_argument("--out-dir", default="src", help="Output directory for generated files")
    args = parser.parse_args()

    classes = load_spec(args.spec)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Generate common
    common = gen_common(classes)
    (out_dir / "rpc_common_generated.rs").write_text(common)
    print(f"  → {out_dir / 'rpc_common_generated.rs'}")

    # Generate target
    target = gen_target(classes)
    (out_dir / "rpc_target_generated.rs").write_text(target)
    print(f"  → {out_dir / 'rpc_target_generated.rs'}")

    # Generate host
    host = gen_host(classes)
    (out_dir / "rpc_host_generated.rs").write_text(host)
    print(f"  → {out_dir / 'rpc_host_generated.rs'}")

    print("Done.")


if __name__ == "__main__":
    main()
