// Auto-generated by generate_rpc.py — DO NOT EDIT
// Source: rpc_protocol.toml

#![allow(dead_code)]
#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(unused_imports)]

use crate::rpc_common_generated::*;
use crate::hosted::rpc_host::remote_encoder::rpc_encoder;
use crate::parsing_util::{u8s_string_to_u32_le, u8s_string_to_u8};
use crate::rn_bmp_cmd_c::platform_buffer_read;

crate::setup_log!(false);
crate::gdb_print_init!();

const RPC_BUFFER_SIZE: usize = 512;
static mut rpc_buffer: [u8; RPC_BUFFER_SIZE] = [0; RPC_BUFFER_SIZE];

fn remote_get_reply() -> &'static [u8] {
    unsafe {
        let buf: *mut u8 = rpc_buffer.as_mut_ptr();
        let se = platform_buffer_read(buf, RPC_BUFFER_SIZE as i32);
        &rpc_buffer[0..(se as usize)]
    }
}

fn check_reply(reply: &[u8], expected: usize) -> bool {
    if reply.is_empty() { return false; }
    if reply[0] != RPC_RESP_OK { return false; }
    if reply.len() != (expected + 1) { return false; }
    true
}

// ── GEN commands ──
pub fn remote_gen_start() -> u32 {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_GEN_PACKET, RPC_GEN_START]);
    e.end();
    let reply = remote_get_reply();
    if !check_reply(reply, 8) { return 0; }
    u8s_string_to_u32_le(&reply[1..])
}

pub fn remote_gen_voltage() -> &'static [u8] {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_GEN_PACKET, RPC_GEN_VOLTAGE]);
    e.end();
    let reply = remote_get_reply();
    reply
}

pub fn remote_gen_nrst_set(assert: bool) -> bool {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_GEN_PACKET, RPC_GEN_NRST_SET]);
    e.add_u8(&[if assert { b'1' } else { b'0' }]);
    e.end();
    let reply = remote_get_reply();
    check_reply(reply, 0)
}

pub fn remote_gen_nrst_get() -> u8 {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_GEN_PACKET, RPC_GEN_NRST_GET]);
    e.end();
    let reply = remote_get_reply();
    if !check_reply(reply, 2) { return 0; }
    u8s_string_to_u8(&reply[1..])
}

pub fn remote_gen_target_clk_oe(enable: bool) -> bool {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_GEN_PACKET, RPC_GEN_TARGET_CLK_OE]);
    e.add_u8(&[if enable { b'1' } else { b'0' }]);
    e.end();
    let reply = remote_get_reply();
    check_reply(reply, 0)
}

pub fn remote_gen_freq_set(freq_khz: u32) -> bool {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_GEN_PACKET, RPC_GEN_FREQ_SET]);
    e.add_u32_le(freq_khz as u32);
    e.end();
    let reply = remote_get_reply();
    check_reply(reply, 0)
}

pub fn remote_gen_freq_get() -> u32 {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_GEN_PACKET, RPC_GEN_FREQ_GET]);
    e.end();
    let reply = remote_get_reply();
    if !check_reply(reply, 8) { return 0; }
    u8s_string_to_u32_le(&reply[1..])
}

pub fn remote_gen_pwr_set(enabled: bool) -> bool {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_GEN_PACKET, RPC_GEN_PWR_SET]);
    e.add_u8(&[if enabled { b'1' } else { b'0' }]);
    e.end();
    let reply = remote_get_reply();
    check_reply(reply, 0)
}

pub fn remote_gen_pwr_get() -> u8 {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_GEN_PACKET, RPC_GEN_PWR_GET]);
    e.end();
    let reply = remote_get_reply();
    if !check_reply(reply, 2) { return 0; }
    u8s_string_to_u8(&reply[1..])
}

// ── SWDP commands ──
pub fn remote_swdp_init() -> bool {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_SWDP_PACKET, RPC_SWDP_INIT]);
    e.end();
    let reply = remote_get_reply();
    check_reply(reply, 0)
}

// ── HL commands ──
pub fn remote_hl_check() -> u8 {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_HL_PACKET, RPC_HL_CHECK]);
    e.end();
    let reply = remote_get_reply();
    if !check_reply(reply, 2) { return 0; }
    u8s_string_to_u8(&reply[1..])
}

pub fn remote_hl_accel() -> u8 {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_HL_PACKET, RPC_HL_ACCEL]);
    e.end();
    let reply = remote_get_reply();
    if !check_reply(reply, 2) { return 0; }
    u8s_string_to_u8(&reply[1..])
}

// ── RV commands ──
pub fn remote_rv_reset() -> (bool, u32) {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_RV_PACKET, RPC_RV_RESET]);
    e.end();
    let reply = remote_get_reply();
    if !check_reply(reply, 8) { return (false, 0); }
    (true, u8s_string_to_u32_le(&reply[1..]))
}

pub fn remote_rv_dm_read(address: u32) -> (bool, u32) {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_RV_PACKET, RPC_RV_DM_READ]);
    e.add_u8_hex(address as u32);
    e.end();
    let reply = remote_get_reply();
    if !check_reply(reply, 8) { return (false, 0); }
    (true, u8s_string_to_u32_le(&reply[1..]))
}

pub fn remote_rv_dm_write(address: u32, value: u32) -> (bool, u32) {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_RV_PACKET, RPC_RV_DM_WRITE]);
    e.add_u8_hex(address as u32);
    e.add_u32_le(value as u32);
    e.end();
    let reply = remote_get_reply();
    if !check_reply(reply, 8) { return (false, 0); }
    (true, u8s_string_to_u32_le(&reply[1..]))
}

// ── LNADIV commands ──
pub fn remote_lnadiv_write(address: u32, data: u32) -> (bool, u32) {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_LNADIV_PACKET, RPC_LNADIV_WRITE]);
    e.add_u16_le(address as u32);
    e.add_u32_le(data as u32);
    e.end();
    let reply = remote_get_reply();
    if !check_reply(reply, 8) { return (false, 0); }
    (true, u8s_string_to_u32_le(&reply[1..]))
}

pub fn remote_lnadiv_read(address: u32) -> (bool, u32) {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_LNADIV_PACKET, RPC_LNADIV_READ]);
    e.add_u16_le(address as u32);
    e.end();
    let reply = remote_get_reply();
    if !check_reply(reply, 8) { return (false, 0); }
    (true, u8s_string_to_u32_le(&reply[1..]))
}

pub fn remote_lnadiv_raw_write(tick_count: u32, value: u32) -> (bool, u32) {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_LNADIV_PACKET, RPC_LNADIV_RAW_WRITE]);
    e.add_u32_le(tick_count as u32);
    e.add_u32_le(value as u32);
    e.end();
    let reply = remote_get_reply();
    if !check_reply(reply, 8) { return (false, 0); }
    (true, u8s_string_to_u32_le(&reply[1..]))
}

pub fn remote_lnadiv_lowlevel(rnw: u32, address: u32, value: u32) -> (u32, u32) {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_LNADIV_PACKET, RPC_LNADIV_LOWLEVEL]);
    e.add_u8_hex(rnw as u32);
    e.add_u16_le(address as u32);
    e.add_u32_le(value as u32);
    e.end();
    let reply = remote_get_reply();
    if !check_reply(reply, 16) {
        return (0, 0);
    }
    (u8s_string_to_u32_le(&reply[1..9]), u8s_string_to_u32_le(&reply[9..17]))
}

// ── ADIV5 commands ──
pub fn remote_adiv5_raw_access_v3(device_index: u32, ap_selection: u32, address: u32, value: u32) -> (u32, u32) {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_ADIV5_PACKET, RPC_ADIV5_RAW_ACCESS_V3]);
    e.add_u8_hex(device_index as u32);
    e.add_u8_hex(ap_selection as u32);
    e.add_u16_be(address as u32);
    e.add_u32(value as u32);
    e.end();
    let reply = remote_get_reply();
    if !check_reply(reply, 16) {
        return (1, 0);
    }
    (u8s_string_to_u32_le(&reply[1..9]), u8s_string_to_u32_le(&reply[9..17]))
}

pub fn remote_adiv5_dp_read(device_index: u32, ap_selection: u32, address: u32) -> (i32, u32) {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_ADIV5_PACKET, RPC_ADIV5_DP_READ]);
    e.add_u8_hex(device_index as u32);
    e.add_u8_hex(ap_selection as u32);
    e.add_u32(address as u32);
    e.end();
    let reply = remote_get_reply();
    if reply.is_empty() || reply[0] != RPC_RESP_OK {
        return (reply.get(1).copied().unwrap_or(1) as i32, 0);
    }
    (0, u8s_string_to_u32_le(&reply[1..]))
}

pub fn remote_adiv5_ap_read(device_index: u32, ap_selection: u32, address: u32) -> (i32, u32) {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_ADIV5_PACKET, RPC_ADIV5_AP_READ]);
    e.add_u8_hex(device_index as u32);
    e.add_u8_hex(ap_selection as u32);
    e.add_u16_be(address as u32);
    e.end();
    let reply = remote_get_reply();
    if reply.is_empty() || reply[0] != RPC_RESP_OK {
        return (reply.get(1).copied().unwrap_or(1) as i32, 0);
    }
    (0, u8s_string_to_u32_le(&reply[1..]))
}

pub fn remote_adiv5_ap_write(device_index: u32, ap_selection: u32, address: u32, value: u32) -> (i32, u32) {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_ADIV5_PACKET, RPC_ADIV5_AP_WRITE]);
    e.add_u8_hex(device_index as u32);
    e.add_u8_hex(ap_selection as u32);
    e.add_u16_be(address as u32);
    e.add_u32(value as u32);
    e.end();
    let reply = remote_get_reply();
    if reply.is_empty() || reply[0] != RPC_RESP_OK {
        return (reply.get(1).copied().unwrap_or(1) as i32, 0);
    }
    (0, u8s_string_to_u32_le(&reply[1..]))
}

pub fn remote_adiv5_mem_read(device_index: u32, ap_selection: u32, csw: u32, address: u32, length: u32) -> (i32, &'static [u8]) {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_ADIV5_PACKET, RPC_ADIV5_MEM_READ]);
    e.add_u8_hex(device_index as u32);
    e.add_u8_hex(ap_selection as u32);
    e.add_u32(csw as u32);
    e.add_u32(address as u32);
    e.add_u32(length as u32);
    e.end();
    let reply = remote_get_reply();
    if reply.is_empty() || reply[0] != RPC_RESP_OK {
        return (reply.get(1).copied().unwrap_or(1) as i32, &[]);
    }
    (0, &reply[1..])
}

pub fn remote_adiv5_mem_write(device_index: u32, ap_selection: u32, csw: u32, align: u32, address: u32, length: u32, data: &[u8]) -> (i32, u32) {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_ADIV5_PACKET, RPC_ADIV5_MEM_WRITE]);
    e.add_u8_hex(device_index as u32);
    e.add_u8_hex(ap_selection as u32);
    e.add_u32(csw as u32);
    e.add_u8_hex(align as u32);
    e.add_u32(address as u32);
    e.add_u32(length as u32);
    // SAFETY: data is valid UTF-8 hex encoding
    e.hex_and_add(unsafe { core::str::from_utf8_unchecked(data) });
    e.end();
    let reply = remote_get_reply();
    if reply.is_empty() || reply[0] != RPC_RESP_OK {
        return (reply.get(1).copied().unwrap_or(1) as i32, 0);
    }
    (0, u8s_string_to_u32_le(&reply[1..]))
}

// ── SWINDLE commands ──
pub fn remote_swindle_crc32(address: u32, length: u32) -> (bool, u32) {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_SWINDLE_PACKET, RPC_SWINDLE_CRC32]);
    e.add_u32_le(address as u32);
    e.add_u32_le(length as u32);
    e.end();
    let reply = remote_get_reply();
    if !check_reply(reply, 8) { return (false, 0); }
    (true, u8s_string_to_u32_le(&reply[1..]))
}

pub fn remote_swindle_get_fq() -> (bool, u32) {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_SWINDLE_PACKET, RPC_SWINDLE_GET_FQ]);
    e.end();
    let reply = remote_get_reply();
    if !check_reply(reply, 8) { return (false, 0); }
    (true, u8s_string_to_u32_le(&reply[1..]))
}

pub fn remote_swindle_set_fq(freq_hz: u32) -> bool {
    let mut e = rpc_encoder::new();
    e.begin();
    e.add_u8(&[RPC_SWINDLE_PACKET, RPC_SWINDLE_SET_FQ]);
    e.add_u32_le(freq_hz as u32);
    e.end();
    let reply = remote_get_reply();
    check_reply(reply, 0)
}

