/*
 */
/**
 * @file bmp_sdiTap_ln.cpp
 * @brief WCH SDI (single wire debug interface) tap for the LN platform.
 *
 * Same abstract interface as bmp_sdiTap_rp2040.cpp (sdi_dm_start/write/read, the
 * bmp_sdi_dm_*_c entry points, sdi_scan, the ch32_sdi_dmi_* leaves and every
 * protocol constant), but no PIO:
 *
 *  - a *write* frame is generated by hardware: a fixed period PWM carrier with
 *    one bit cell per compare event, and the per-cell duty (CHCV = the cell's
 *    LOW time) fed by DMA, so the CPU only starts it and waits for the drain,
 *  - a *read* frame is that same carrier: its nine header cells plus 32 read
 *    clock cells in one DMA packet, with the pad handed over in *open drain* so
 *    every HIGH is a release (the target drives the response bits there) and the
 *    level shifter's turn-around fired by two more timer channels through the
 *    DMA at the boundary and at the release, so the direction change and the
 *    clock edge are one instant. The CPU only waits for the cell boundary (the
 *    update flag) and reads the pad at the sample tick: ~3 bus accesses per cell,
 *    all of it inside lnNoInterrupt()/lnInterrupts() (a 1 kHz class ISR inside a
 *    cell would push a sample past the boundary).
 *
 * The read half used to be CPU timed, i.e. the CPU making every edge, and that
 * does not fit in a cell: 86 ticks at 96 MHz against four pad stores plus the
 * boundary poll, ~10 bus accesses at ~9 cycles each. Measured, a hand made read
 * cell came out at 1.5 us and the target was handed a clock 1.7x too slow - a
 * *wrong* clock, not a slow one - and the protocol's own windows ((T,2T) LOW,
 * (T,8T) HIGH, sdi.txt §2) leave no room to stretch the cell and buy the CPU the
 * time either. See §13 of the plan.
 *
 * The bit cell, the frame layout and every protocol constant are shared with the
 * RP2040 tap (sdi.pio, sdi.txt); only the way the waveform is produced differs.
 * Building with -DSDI_LN_BITBANG_TX moves the write frames to the same CPU timed
 * path (timer as clock, no DMA, no channel output), which is what isolates the
 * TX engine when a new board is brought up.
 *
 * Pins: the SDI wire is the SWDIO line, _mapping[TSWDIO_PIN] (PB8), whose
 * pinMappings entry maps it to timer 3 channel 2, i.e. TIMER4_CH3;
 * _mapping[TDIRECTION_PIN] (PC3) is the level shifter direction, already owned by
 * SwdDirectionPin *rSWDIO (bmp_tap_ln.cpp). NRST is driven through the shared
 * SwdReset controller so the build time polarity option is honoured.
 */

// -------------------------------------------------- //
#include "lnGPIO.h"
#include "lnDma.h"
#include "lnTimer.h"
#include "lnTimer_priv.h"
#include "lnPinMapping.h"
#include "stdint.h"
#include "esprit.h"
#include "bmp_pinmode.h"
#include "bmp_pinout.h"
#include "bmp_tap_ln.h"
#include "lnBMP_pins.h"
#include "lnBMP_reset.h"
#include <cstring>

// The blackmagic RISC-V target framework (riscv_debug.h) is needed for the
// Stage-2 attach below: we hand riscv_dmi_init() an SDI-backed riscv_dmi_s,
// exactly mirroring what rvswd_template.h::rvswd_scan() does over RVSWD.
extern "C"
{
#include "jep106.h"
#include "riscv_debug.h"
extern "C" void target_list_free(void);

/* SDI data pin: the same physical wire the SWD/RVSWD taps use, i.e. the SWDIO
 * line _mapping[TSWDIO_PIN] (PB8 on both packages).
 *
 * PB8 has to change role inside a frame (the timer drives the wire during a
 * write frame, the pad's open drain pulls it low for the read frame's clock
 * pulses and samples it when the target drives) and the level shifter direction
 * has to follow, so both are done through rSWDIO: _fast is the pad's BOP
 * set/clear word and _fastdir the direction pin, both single stores. */
#define SDI_DATA_PIN _mapping[TSWDIO_PIN]

// ---------------------------------------------------------------------------
// Platform transport hooks consumed by the shared protocol layer.
//
// The SDI protocol itself (DM/configuration registers, §2.4 shadow/commit, frame
// format, CPBR diagnostics, DMI glue and the RISC-V attach) lives in
// ../../template/sdi_template.h, shared with the other platforms. This file owns
// the wire: the timer/DMA write frame and the CPU-timed read frame below.
//
// The hooks are macros, not functions: the template only ever calls them once
// per frame (never inside a bit cell), so the indirection costs nothing and the
// frame-level code expands to exactly the same source on every platform.
// ---------------------------------------------------------------------------
static void sdiWriteFrame(const uint8_t adr, const uint32_t data);
static uint32_t sdiReadFrame(const uint8_t adr);

#define sdiFrameWrite(adr, val) sdiWriteFrame((adr), (val))
#define sdiFrameRead(adr) sdiReadFrame(adr)
/* §2.4(3): hold the wire low for @p ms, then let it float high again. The pulse
 * has to come from the pad itself - DIR back to the probe, ODR 0 sinks it, and
 * releasing ODR lets the level shifter's pull-up float the wire high. */
#define sdiWireHoldLow(ms)                                 \
    do                                                     \
    {                                                      \
        rSWDIO->_fastdir.on(); /* DIR = probe */           \
        rSWDIO->_fast.off();   /* Drive LOW */             \
        lnDelayMs(ms);                                     \
        rSWDIO->_fast.on();    /* Release to float HIGH */ \
    } while (0)

/* The shared protocol layer (sdi_dm_start/write/read, bmp_sdi_dm_*_c,
 * ch32_sdi_dmi_read/write, sdi_scan). Requires: bmp_pinmode.h, pReset,
 * rSWDIO/bmp_tap_ln.h, Logger/lnDelayMs/lnDelayUs, <cstring> and the blackmagic
 * RISC-V target framework, all included above. */
#include "sdi_template.h"



/* Bit cell (§2.2, T = 896 ns for the 1x time base the RP2040 tap was measured
 * against). One cell = one LOW pulse whose length selects the bit, then HIGH
 * until the next cell. The response is sampled at 616 ns (the point sdi.pio
 * settles on, ~116 ns above the 500 ns the text guarantees for the shortest
 * data-0 LOW) and the data stays valid until the end of the cell, so the CPU has
 * the rest of the cell to read the pin and re-arm for the next boundary.
 *
 * Every one of those times is an exact fraction of the cell (1/4, 11/16, 3/4),
 * so they are derived from the cell length in ticks instead of asking the timer
 * clock again: one clock measurement per session, and the split stays exact
 * whatever the clock does. */
#define SDI_TBIT_NS 896u
#define SDI_LOW1_NUM 1u /* LOW1 = 1/4 cell, 224 ns */
#define SDI_LOW1_DEN 4u
#define SDI_RX_SAMPLE_NUM 11u /* sample = 11/16 cell, 616 ns */
#define SDI_RX_SAMPLE_DEN 16u

/* Cell frequency handed to lnDmaTimer, which measures the timer clock (and knows
 * about the ARM APB1 x2 workaround) and turns this into CAR: one compare event
 * per cell, i.e. 86 ticks at 96 MHz and 129 at 144 MHz. */
#define SDI_CELL_HZ (1000000000u / SDI_TBIT_NS)

/* Extra ticks added to a CPU generated LOW. The pad is pulled low a couple of
 * cycles after the cell boundary, so without this the pulse would be *shorter*
 * than the 224 ns minimum; the extra ticks keep a CPU made low at or above the
 * intended length instead. The cell length never depends on it: that always
 * comes from the timer. */
#define SDI_CPU_LOW_EXTRA_TICKS 2

/* The response cells' DIR turn-around, made by the timer's own DMA (see §13).
 *
 * PC3 is the level shifter's direction pin and is *not* a timer channel, so the
 * transition cannot come from a channel output: it comes from a channel's compare
 * event, which fires a DMA transfer into the pad's BOP - the same store
 * _fastdir.on()/off() makes by hand - at the tick the carrier releases the wire.
 * Two channels are needed because the two transitions are at different ticks;
 * both are used without a pin (CHxEN stays cleared), so they are two clocks, not
 * two outputs:
 *
 *   TIM4_CH1, CHCV = 0     ->  DIR = probe   at the cell boundary
 *   TIM4_CH2, CHCV = LOW1  ->  DIR = target  at the release
 *
 * That is what a read frame needs and what the CPU cannot do: a CPU made
 * turn-around lands 100-400 ns after the release (the move costs four pad stores
 * plus the boundary poll against a cell of 86 ticks, ~10 bus accesses at ~9
 * cycles each), and for that window the shifter drives the wire while the target
 * is driving its own data.
 */
#define SDI_DIR_PIN _mapping[TDIRECTION_PIN]
#define SDI_DIR_PROBE_CH 0  /* TIM4_CH1: fired at the boundary */
#define SDI_DIR_TARGET_CH 1 /* TIM4_CH2: fired at the release */

/**
 * @brief ticks * num / den, rounded up.
 *
 * Used for the LOW times and the sample point: those have documented minima
 * (§2.2), so they round up rather than to nearest.
 */
static uint32_t sdiTicksUp(uint32_t ticks, uint32_t num, uint32_t den)
{
    return (ticks * num + den - 1) / den;
}

}
// ---------------------------------------------------------------------------
// Cell engine.
//
// The RP2040 drives the whole frame from one PIO state machine; here the two
// halves of a frame are produced differently:
//
//   write frame : a fixed period PWM carrier, one cell per compare event, the
//                 duty (= the cell's LOW time) coming from DMA, so the nine
//                 cells of a header and the 32 of a payload cost no CPU time,
//   read frame  : the timer is reduced to a clock, the CPU makes the cells.
//
// PWM mode 2 (esprit's lnTimerModePwm1, OCxM = 111) is what makes CHCV mean "the
// LOW time of the cell" and makes a duty of 0 mean "never low", so the stop cell
// needs no special case. OCxPE (LN_TIME_CHCTL0_SEN) is enabled so the duty the
// DMA writes during cell k becomes active at the start of cell k+1.
// ---------------------------------------------------------------------------
extern LN_Timers_Registers *abTimers[5];
#define aTimer(x) abTimers[x]

/* The pin -> (timer, channel) and (timer, channel) -> (DMA engine, DMA channel)
 * lookups, and the DMA channel object itself, are lnDmaTimer's: its constructor
 * walks pinMappings and timerMappings with the same key (10 * timer + channel)
 * and allocates the lnDMA (16 bit memory -> 16 bit CHCV, which is what the cell
 * duties need). PB8 is timer 3 / channel 2, whose entry is {32, 0, 4}, i.e.
 * engine 0 channel 4 - the request line TIMER4_CH3 is wired to on both parts. */

/**
 * @brief A placeholder callback: the engine polls the hardware, it never uses the
 *        transfer interrupt, and every SDI transfer has its channel's interrupt
 *        disabled as soon as it is armed (see armDmaFrame()). It stays attached
 *        because esprit's invokeCallback() xAsserts on a missing callback, so
 *        this is what turns a completion that did arrive into a no-op rather than
 *        a dead end.
 */
static void sdiDmaDone(void *cookie, lnDMA::DmaInterruptType typ)
{
    (void)cookie;
    (void)typ;
}

/**
 * @brief Fixed period SDI cell engine (PWM + DMA for write frames, counter only
 *        for the CPU timed ones).
 *
 * lnDmaTimer is the base and does the discovery: the pin's timer/channel, that
 * channel's DMA channel, the lnDMA object, and the counter setup derived from the
 * cell frequency (including the ARM APB1 x2 workaround). Only the layer above it
 * is SDI specific: a frame is *one shot* - a preloaded first duty, a sentinel
 * stop cell, the transfer counter polled afterwards - where lnDmaTimer::start()
 * is circular, interrupt driven and starts on rollover/2; and the CPU timed half
 * of a frame needs the bare counter as a clock, which lnTimer does not expose.
 */
class SdiTimer : public lnDmaTimer
{
  public:
    /** 16 bit duties: one cell per compare event, CHCV = that cell's LOW time. */
    SdiTimer(lnPin pin) : lnDmaTimer(16, pin)
    {
        _t = aTimer(_timer);
        _period = _low1 = _low0 = _sample = 0;
        // The compare request has to win the bus before the next cell starts.
        _dma->setPriority(lnDMA::DMA_PRIORITY_ULTRA_HIGH);
    }
    /** Measure the timer clock, set the cell period, prepare the channel. */
    void configure();
    //-- hardware generated frames (write)
    void armDmaFrame(uint16_t *duties, int cells);
    void releaseCells();
    void waitDrained();
    void waitSentinelCell();
    void stopDmaFrame();
    //-- CPU timed frames (read, and every frame with SDI_LN_BITBANG_TX)
    void startClock();
    void stopClock();
    void waitCellStart();
    void waitTick(uint32_t tick);
    bool waitCellBoundary();
    //-- derived tick counts
    uint32_t low1() const
    {
        return _low1;
    }
    uint32_t low0() const
    {
        return _low0;
    }
    uint32_t period() const
    {
        return _period;
    }
    uint32_t sampleTick() const
    {
        return _sample;
    }
    void logTicks();
    //-- the shifter's direction, made by the timer during the read frames
    void setupDirDma();
    void armDirFrame();
    void disarmDirFrame();

  protected:
    LN_Timers_Registers *_t;
    uint32_t _period, _low1, _low0, _sample;
    /* The two DIR channels and their DMA. _dirWord[0] is what a store of "probe"
     * writes (exactly _fastdir.on()), _dirWord[1] what "target" writes, both to
     * the same register. They live in the object, i.e. in RAM, because the DMA
     * reads them. */
    lnDMA *_dirDma[2];
    volatile uint32_t *_dirRegister;
    uint32_t _dirWord[2];
    /* One word per compare event of a read frame: the nine header cells keep DIR =
     * probe (the probe drives both levels there), the 32 response cells turn it to
     * the target at their release, and the stop cell turns it back. Laid out once,
     * armed as a whole before the clock starts (armDirFrame()), so the phase cannot
     * depend on when the CPU got around to it. */
    uint32_t _dirFrame[SDI_HEADER_BITS + SDI_WORD_BITS + 1];
    uint32_t dirDmaChannel(int channel) const;
    uint32_t readChannelCtl(int channel) const;
    void writeChannelCtl(int channel, uint32_t value);
};

/** @brief The 8-bit channel control word of one of the timer's channels. */
uint32_t SdiTimer::readChannelCtl(int channel) const
{
    return (_t->CHCTLs[channel >> 1] >> (8 * (channel & 1))) & 0xff;
}

void SdiTimer::writeChannelCtl(int channel, uint32_t value)
{
    const int shift = 8 * (channel & 1);
    uint32_t reg = _t->CHCTLs[channel >> 1];
    reg &= ~(0xffU << shift);
    reg |= (value & 0xffU) << shift;
    _t->CHCTLs[channel >> 1] = reg;
}

/**
 * @brief The DMA channel a timer channel's compare event is wired to.
 *
 * The same lookup lnDmaTimer's constructor does (timerMappings, key
 * 10 * timer + channel), repeated here for the two DIR channels, which have no
 * lnDmaTimer of their own. Returns (engine << 8) | channel.
 */
uint32_t SdiTimer::dirDmaChannel(int channel) const
{
    const int key = 10 * _timer + channel;
    for (const LN_TIMER_MAPPING *m = timerMappings; m->TimerChannel != -1; m++)
    {
        if (m->TimerChannel == key)
            return ((uint32_t)m->dmaEngine << 8) | ((uint32_t)m->dmaChannel & 0xff);
    }
    xAssert(0);
    return 0;
}

/**
 * @brief Build the two DIR channels and their DMA. Once per SDI session.
 *
 * The channels are *compare sources* only: CHxEN is left cleared, so they cannot
 * drive a pin (their pins are not even configured), and what is set is the PWM
 * mode - so the compare behaves exactly like the carrier's channel, whose DMA is
 * the proven part of this file - plus the CCxDE request. CHCV is the tick of the
 * transition: 0 for the boundary, LOW1 for the release, i.e. the same tick the
 * carrier's own compare lets the wire go at.
 *
 * The boundary's DIR is one word written at every boundary, so that channel is
 * armed once, circularly (see the tail of this function). The release's DIR is a
 * whole frame's word sequence instead - only the response cells turn around - and
 * armDirFrame() arms it per read frame, before the clock starts.
 */
void SdiTimer::setupDirDma()
{
    const int channels[2] = {SDI_DIR_PROBE_CH, SDI_DIR_TARGET_CH};

    /* The direction pin is the SWD direction pin, already a fast IO: take the
     * register and the two words from it instead of recomputing them. */
    _dirRegister = rSWDIO->_fastdir.fastRegister();
    _dirWord[0] = rSWDIO->_fastdir.fastSetWord();   // probe drives the wire
    _dirWord[1] = rSWDIO->_fastdir.fastClearWord(); // target drives the wire

    /* The read frame's word sequence: the header's nine compare events keep the
     * direction where it is (a write-like section), the 32 response cells' own
     * compare events turn it around at their release, and the stop cell's turns it
     * back. */
    for (int i = 0; i < SDI_HEADER_BITS; i++)
        _dirFrame[i] = _dirWord[0];
    for (int i = 0; i < SDI_WORD_BITS; i++)
        _dirFrame[SDI_HEADER_BITS + i] = _dirWord[1];
    _dirFrame[SDI_HEADER_BITS + SDI_WORD_BITS] = _dirWord[0];

    for (int i = 0; i < 2; i++)
    {
        const int channel = channels[i];
        const uint32_t dma = dirDmaChannel(channel);

        _dirDma[i] = new lnDMA(lnDMA::DMA_MEMORY_TO_PERIPH, (int)(dma >> 8), (int)(dma & 0xff), 32, 32);
        _dirDma[i]->setPriority(lnDMA::DMA_PRIORITY_ULTRA_HIGH);
        _dirDma[i]->attachCallback(sdiDmaDone, NULL);

        writeChannelCtl(channel, LN_TIME_CHCTL0_CTL_PWM1);
        _t->CHCTL2 &= ~LN_TIMER_CHTL2_CHxEN(channel);      // no pin: the compare alone
        _t->CHCVs[channel] = (i == 0) ? 0 : _low1;         // the boundary / the release
        _t->DMAINTEN |= LN_TIMER_DMAINTEN_CHxDEN(channel); // a request per compare
    }
    _t->CTL1 |= LN_TIMER_CTL1_DMAS; // both requests go through the DMA

    /* The boundary's DIR is the steady state of every frame (a write frame drives
     * both levels with DIR = probe) and the same word every time, so this channel
     * is armed once, circularly, and from then on it re-writes it at every cell of
     * every frame. The release's DIR = target is not: only the response cells turn
     * around, so that one is a per-frame word sequence (armDirFrame()). */
    _dirDma[0]->beginTransfer();
    _dirDma[0]->doMemoryToPeripheralTransferNoLock(1, (const uint16_t *)&_dirWord[0], (const uint16_t *)_dirRegister,
                                                   true, true, false);
    /* Its completion is not news either: it re-writes the same word at every
     * compare event of every frame. See armDmaFrame() for why the SDI transfers
     * run with their channel's interrupt disabled. */
    _dirDma[0]->disableInterrupt();
}

/**
 * @brief Arm the DIR word sequence of a read frame: one word per compare event.
 *
 * Forty-two items, laid out in setupDirDma(): nine "probe" for the header (the
 * probe drives both levels there), 32 "target" for the response cells - each one
 * fired at that cell's release, i.e. by the very compare event that lets the wire
 * go - and one "probe" for the stop cell.
 *
 * Armed as a whole *before* the clock starts, so there is no timing constraint on
 * it at all: the first compare after releaseCells() is cell 0's, which makes the
 * phase the frame's rather than the CPU's. Arming it in the middle of the frame
 * would not do: cell 9's release is 22 ticks into its cell, which is not enough
 * for two DMA calls, and a late arm would leave that release (and the whole first
 * response bit) with the probe still driving the wire.
 */
void SdiTimer::armDirFrame()
{
    _dirDma[1]->beginTransfer();
    /* endTransfer() -> cancelTransfer() (lnDma.cpp) clears both the channel's
     * callback and its registration, and this channel is disarmed at the end of
     * every read frame (disarmDirFrame()), so both are re-made here rather than
     * once per session: esprit's invokeCallback() xAsserts on a missing callback,
     * and beginTransfer() xAsserts on a registration that is still in place. */
    _dirDma[1]->attachCallback(sdiDmaDone, NULL);
    _dirDma[1]->doMemoryToPeripheralTransferNoLock(SDI_HEADER_BITS + SDI_WORD_BITS + 1, (const uint16_t *)_dirFrame,
                                                  (const uint16_t *)_dirRegister, false, false, false);
    /* No completion interrupt, for the reason armDmaFrame() gives at length - it is
     * the *carrier's* completion that lands inside the masked read frame, and this
     * one shares the rule so that no SDI transfer can ever be the deferred
     * interrupt dmaIrqHandler() turns into a dead end. Its own 42nd item (the stop
     * cell's, at the tick the carrier releases there) is a race either way, since
     * stopDmaFrame() clears CEN within `_low1` ticks + a few hundred ns of the stop
     * cell starting: if it is delivered it writes `_dirWord[0]` (probe, the state
     * the frame ends in), and if it is not, disarmDirFrame() cancels it. */
    _dirDma[1]->disableInterrupt();
}

/**
 * @brief Release the DIR = target channel again, at the end of a read frame.
 *
 * lnDMA::beginTransfer() takes the channel's mutex and only endTransfer() gives
 * it back, so the next frame's arm would block on it without this. The transfer
 * itself has already run its 42 compares and stopped there.
 */
void SdiTimer::disarmDirFrame()
{
    _dirDma[1]->endTransfer();
}

/** @brief Report the derived cell timings, so a clock mismatch is visible. */
void SdiTimer::logTicks()
{
    Logger("SDI : timer %d channel %d : cell %u ticks, LOW1 %u, LOW0 %u, sample %u\n", (int)_timer, (int)_channel,
           (unsigned)_period, (unsigned)_low1, (unsigned)_low0, (unsigned)_sample);
}

/**
 * @brief Configure the carrier: one compare event per cell, PWM mode 2 with the
 *        preload on, compare DMA request enabled, counter stopped.
 *
 * The cell period comes from lnDmaTimer::pwmSetup(), i.e. from one measurement of
 * the timer clock (APB1 x2 workaround included), and is read back as rollover().
 * LOW1, the sample point and LOW0 are then exact fractions of that period rather
 * than a second measurement, so they cannot drift against the cell: 86 ticks give
 * 22 / 64 / 60 at 96 MHz, 129 give 33 / 96 / 89 at 144 MHz.
 *
 * CHCV is left at 0, i.e. the channel output is HIGH: that is the state the pad
 * is handed over to the timer in, so the hand-over produces no edge.
 */
void SdiTimer::configure()
{
    pwmSetup((int)SDI_CELL_HZ);
    setMode(lnTimerModePwm1); // pwmSetup() leaves the channel in PWM mode 1
    _period = (uint32_t)rollover();

    _low1 = sdiTicksUp(_period, SDI_LOW1_NUM, SDI_LOW1_DEN);
    if (_low1 < 1)
        _low1 = 1;
    if (_low1 >= _period)
        _low1 = _period - 1;
    _low0 = _period - _low1; // keep the split exact: LOW1 + LOW0 == period, so LOW0 comes out
                             // at 672 ns minus the rounding of LOW1 (667 ns at 96/144 MHz)
    _sample = sdiTicksUp(_period, SDI_RX_SAMPLE_NUM, SDI_RX_SAMPLE_DEN);
    if (_sample < _low1 + 1)
        _sample = _low1 + 1; // the sample must follow the clock LOW
    if (_sample >= _period)
        _sample = _period - 1; // and it must stay inside the cell

    _t->CTL0 &= ~LN_TIMER_CTL0_CEN;
    writeChannelCtl(_channel, readChannelCtl(_channel) | LN_TIME_CHCTL0_SEN); // OCxPE: shadowed duty
    _t->CHCTL2 &= ~(LN_TIMER_CHTL2_CHxP(_channel));         // active high
    _t->CHCTL2 |= LN_TIMER_CHTL2_CHxEN(_channel);           // stays enabled for the session
    _t->CHCVs[_channel] = 0;                            // duty 0: never low, i.e. the wire idles high
    _t->DMAINTEN |= LN_TIMER_DMAINTEN_CHxDEN(_channel); // request on the compare event
    _t->CTL1 |= LN_TIMER_CTL1_DMAS;                     // the DMA is the request source
    _t->INTF = 0;
    _t->SWEV |= LN_TIMER_SWEVG_UPG; // commit CAR/CHCV to the active registers

    // The two DIR channels: the read frames' shifter turn-around (§13), armed
    // once here and fired by the timer from then on.
    setupDirDma();
}

/**
 * @brief Arm the DMA with the per-cell duties and preload the first one.
 *
 * The pad is still in open drain here, so nothing of this reaches the wire. The
 * CPU writes CHCV (the shadow register, the preload is on) and generates an
 * update event to commit it, then points the DMA at CHCV for the remaining
 * cells: a copy made at cell k's compare event becomes active at the start of
 * cell k+1.
 *
 * @param duties duties[0] is the first cell (preloaded here), duties[1..cells-1]
 *               the cells the DMA feeds; duties[cells] is overwritten with the
 *               stop cell (duty 0 = never low, i.e. the wire stays high).
 * @param cells  Number of real cells, i.e. duties[1..cells] are transferred.
 *
 * The channel's completion interrupt is disabled right after the transfer is
 * armed, and that is load bearing, not an optimisation: a read frame runs inside
 * lnNoInterrupt()/lnInterrupts() (ENTER_CRITICAL/EXIT_CRITICAL, counter based, so
 * nested), the transfer drains *inside* that window (the 41st compare event), so
 * a completion interrupt would be latched pending and taken when the frame lifts
 * the mask - by which time stopDmaFrame() has already run endTransfer(), i.e.
 * cancelTransfer() has set _lnDmas[][] back to NULL, and esprit's
 * dmaIrqHandler() xAsserts on exactly that (xAssert(la), lnDma.cpp:529) ->
 * do_assert() -> deadEnd(). That abort lands one frame after a write, with the
 * write's own "SDI : write ..." line as the last thing on the console, which is
 * how it was found. Nothing here needs the interrupt anyway: the engine polls
 * getCurrentCount(), the update flag and the counter.
 */
void SdiTimer::armDmaFrame(uint16_t *duties, int cells)
{
    xAssert(cells > 0);
    duties[cells] = 0; // stop cell
    _t->CNT = 0;
    _t->CHCVs[_channel] = duties[0];
    _t->SWEV |= LN_TIMER_SWEVG_UPG; // latch the first duty
    _t->INTF = 0;
    _dma->beginTransfer();
    _dma->attachCallback(sdiDmaDone, NULL);
    _dma->doMemoryToPeripheralTransferNoLock(cells, (const uint16_t *)(duties + 1),
                                             (const uint16_t *)&_t->CHCVs[_channel], false, false, false);
    _dma->disableInterrupt();
}

/** @brief Start the carrier: cell 0 begins here and its LOW is duties[0]. */
void SdiTimer::releaseCells()
{
    _t->CNT = 0;
    _t->CTL0 |= LN_TIMER_CTL0_CEN;
}

/** @brief Wait until the DMA has handed over the stop cell. */
void SdiTimer::waitDrained()
{
    while (_dma->getCurrentCount() != 0)
        ;
}

/** @brief Wait for the start of the stop cell: the wire is high from there on. */
void SdiTimer::waitSentinelCell()
{
    waitCellStart();
}

/**
 * @brief Stop the carrier and release the DMA channel.
 *
 * The channel stays enabled (CHxEN is not cleared): PB8 only reaches the timer in
 * alternate function, so an enabled channel cannot touch the wire while the pad is
 * a GPIO, and leaving it enabled is what makes frame 2..n work - the pad is
 * switched to alternate function *before* the next header is latched, and the
 * channel has to be able to drive the first falling edge from there.
 */
void SdiTimer::stopDmaFrame()
{
    _t->CTL0 &= ~LN_TIMER_CTL0_CEN;
    _t->CNT = 0;
    _dma->endTransfer();
}

/** @brief Start the counter alone: it is the time base of the CPU timed cells. */
void SdiTimer::startClock()
{
    _t->CNT = 0;
    _t->CTL0 |= LN_TIMER_CTL0_CEN;
}

void SdiTimer::stopClock()
{
    _t->CTL0 &= ~LN_TIMER_CTL0_CEN;
    _t->CNT = 0;
}

/**
 * @brief Wait for a cell boundary by waiting for the counter's LOW window.
 *
 * CNT is in its LOW window, i.e. it has just wrapped: the counter never stops,
 * so a cell starts every period whatever the channel does. The window is _low1
 * ticks wide (22 at 96 MHz, 229 ns), which is *not* enough slack to make this
 * safe on its own: a poll that arrives a tick after the window closed - which is
 * one overrun instruction at this clock, with a cell of 86 ticks and the code
 * running from flash - waits for the following wrap and a cell is dropped. That
 * is what the read frames' response cells did (waitCellBoundary() is the
 * latch-based wait the 32 response cells use instead).
 */
void SdiTimer::waitCellStart()
{
    while (_t->CNT >= _low1)
        ;
}

/** @brief Wait until the counter reaches @p tick inside the current cell. */
void SdiTimer::waitTick(uint32_t tick)
{
    while (_t->CNT < tick)
        ;
}

/** @brief The tick inside the current cell, 16 bit like the counter itself. */
/**
 * @brief Wait for the next cell boundary, and never drop a cell.
 *
 * The counter wraps once per cell and the update flag latches that rollover, so
 * a boundary that arrived while the CPU was busy is *taken late* instead of being
 * skipped - and now that the timer makes the read cells (see the DIR channels and
 * sdiSampleWord()) "late" only means the sample that follows moves a few ticks
 * later inside the same cell, never that a clock edge is missing. That matters:
 * a dropped clock edge is a wrong clock (the target's bit counter has no way to
 * know, and its response to the dropped clock is never sampled), while a late
 * sample still reads the bit the target is holding until the next falling edge.
 *
 * Both callers come here straight from the previous boundary, so the flag is
 * clear on entry and every call waits a full cell: nothing has to be cleared
 * first. (The old "return at once when the counter is inside its LOW window"
 * shortcut was for a caller that had just been through waitCellStart(), which
 * the read frame no longer is.)
 *
 * @return true when the boundary was already late, i.e. the CPU did not keep up
 *         with the cells. A diagnostic only: the target sees no difference.
 */
bool SdiTimer::waitCellBoundary()
{
    const bool late = (_t->INTF & LN_TIMER_INTF_UPIF) != 0;
    if (!late)
    {
        while (!(_t->INTF & LN_TIMER_INTF_UPIF))
            ;
    }
    _t->INTF = 0;
    return late;
}
// ---------------------------------------------------------------------------
// Pin role, cell builders and the two frame generators.
// ---------------------------------------------------------------------------
static SdiTimer *sdiTimer = NULL; // created on entering SDI mode
static bool sdiMode = false;      // SDI owns PB8 / PC3
/* Cells the last read frame took late, and whether that has been reported: the
 * only in-firmware evidence that the CPU timed cells fit in a cell time. */
static uint32_t sdiRxLateCells = 0;
static bool sdiRxLateReported = false;

#ifndef SDI_LN_BITBANG_TX
// The two role switches below are only used by the hardware (timer + DMA) frame
// generator: with SDI_LN_BITBANG_TX the pad stays in open drain and the CPU
// makes every cell, so nothing needs to move PB8 in or out of the timer.
/**
 * @brief Hand PB8 to the timer channel (alternate function), channel output high.
 *
 * The output register is set before the pad changes role, and the channel's duty
 * is still 0 at this point (its output is high), so the wire is high before and
 * after: the hand-over itself produces no edge. The first falling edge of the
 * frame is the preloaded duty that armDmaFrame() writes right after.
 */
static void sdiPinToTimer()
{
    rSWDIO->_fast.on();    // keep the ODR bit consistent for the way back
    rSWDIO->_fastdir.on(); // DIR = probe
    lnPinMode(SDI_DATA_PIN, lnPWM, SWD_IO_SPEED);
}

#endif // SDI_LN_BITBANG_TX

/**
 * @brief Hand PB8 to the timer channel as an *open drain* AF output (read frames).
 *
 * A read frame's cells are made by the channel exactly like a write's (one
 * compare event per cell, CHCV = the cell's LOW time), but the release has to be
 * a high-Z: the target drives the wire during the second half of every response
 * cell, and with the pad still driving (AF push-pull, the write's mode) the probe
 * would read its own level instead. `lnALTERNATE_OD` keeps the channel as the
 * source of the LOW and leaves the HIGH to the level shifter, i.e. exactly the
 * pair of levels a CPU made read cell produced by hand.
 *
 * This is the one thing the CPU timed read frame could not do: keep its own
 * clock. A response cell needs four pad stores (the LOW, the release, and the
 * shifter's two turns) plus the boundary poll, ~10 bus accesses at ~9 cycles
 * against a cell of 86 ticks, and the cell had to be pulled out of the timer's
 * latch instead, i.e. the target saw a 1.5 us clock. The timer sees all of it
 * with no CPU at all.
 */
static void sdiPinToTimerOpenDrain()
{
    rSWDIO->_fastdir.on(); // DIR = probe: the probe makes the LOW and the release
    lnPinMode(SDI_DATA_PIN, lnALTERNATE_OD, SWD_IO_SPEED);
}

/**
 * @brief Give PB8 back as an open drain, released.
 *
 * The channel output is high (the stop cell) and the output register is set
 * before the pad stops being driven by the timer, so the wire goes from
 * driven-high to pulled-high. From here on the pad can pull the wire low
 * (switch()) and read it (read()) - and, in the bitbang build, make the cells
 * itself.
 */
static void sdiPinToOpenDrain()
{
    rSWDIO->_fast.on();                              // ODR = 1: released
    lnPinMode(SDI_DATA_PIN, lnOUTPUT_OPEN_DRAIN, 1); // open drain, latch or sense
}

/** @brief The LOW time that carries @p bit: 1 is short, 0 is long (§2.2). */
static inline uint16_t sdiDutyForBit(uint32_t bit)
{
    return bit ? (uint16_t)sdiTimer->low1() : (uint16_t)sdiTimer->low0();
}

/** @brief Fill @p duties with the nine header cells, start bit first. */
static int sdiBuildHeader(uint16_t *duties, uint8_t adr, uint8_t mode)
{
    const uint32_t header = make_sdi_header(adr, mode);
    for (int i = 0; i < SDI_HEADER_BITS; i++)
        duties[i] = sdiDutyForBit((header >> (SDI_HEADER_BITS - 1 - i)) & 1U);
    return SDI_HEADER_BITS;
}

/** @brief Fill @p duties with the 32 payload cells, MSB first (sdi.pio order). */
static int sdiBuildWord(uint16_t *duties, uint32_t data)
{
    for (int i = 0; i < SDI_WORD_BITS; i++)
        duties[i] = sdiDutyForBit((data >> (SDI_WORD_BITS - 1 - i)) & 1U);
    return SDI_WORD_BITS;
}

#ifdef SDI_LN_BITBANG_TX
/**
 * @brief Make @p cells with the CPU, the timer supplying only the cell clock.
 *
 * Only the bring-up build uses this: it is the CPU timed write path, i.e. the
 * one that isolates the TX engine from the timer channel and the DMA. The read
 * frames do not have a CPU timed variant any more - a hand made cell needs ~10
 * bus accesses against a cell of 86 ticks and cannot keep its own clock (§13),
 * which is why the timer makes both halves of a read frame now.
 *
 * DIR is put back to "probe" for the LOW: the level shifter has to pass it, and
 * the pad is pulled low a couple of cycles after the boundary, which is what
 * SDI_CPU_LOW_EXTRA_TICKS compensates for (224 ns is a minimum, not a target).
 */
static void sdiSendCpuCells(const uint16_t *duties, int cells)
{
    for (int i = 0; i < cells; i++)
    {
        sdiTimer->waitCellStart();
        rSWDIO->_fastdir.on(); // DIR = probe: the clock low must reach the wire
        rSWDIO->_fast.off();   // sink: clock LOW
        sdiTimer->waitTick(duties[i] + SDI_CPU_LOW_EXTRA_TICKS);
        rSWDIO->_fast.on(); // release: HIGH until the next boundary
    }
}
#endif // SDI_LN_BITBANG_TX

/**
 * @brief Send one frame of @p cells cells and leave the wire idling high.
 *
 * duties[0..cells-1] are the real cells, contiguous cell by cell (the cell clock
 * never stops inside a frame); duties[cells] is the stop cell, written by
 * armDmaFrame() (duty 0, i.e. never low). A write passes its 41 cells in one
 * call, see sdiWriteFrame().
 */
static void sdiSendFrame(uint16_t *duties, int cells)
{
#ifdef SDI_LN_BITBANG_TX
    // CPU paced variant: no channel output and no DMA, the timer is a clock
    // only. Same duties, so the waveform is the one the hardware path aims at.
    sdiTimer->startClock();
    sdiSendCpuCells(duties, cells);
    sdiTimer->waitTick(sdiTimer->period() - 1); // the stop cell
    sdiTimer->stopClock();
#else
    sdiPinToTimer();
    sdiTimer->armDmaFrame(duties, cells);
    sdiTimer->releaseCells();
    sdiTimer->waitDrained();
    sdiTimer->waitSentinelCell(); // the wire is high from here on
    sdiTimer->stopDmaFrame();
    sdiPinToOpenDrain();
#endif
}

/**
 * @brief The pad's level, without lnDigitalRead()'s port lookup and call.
 *
 * A response cell has 26 ticks of slack after its sample (tick 60 to the next
 * boundary at 86, and 48 before that boundary's window closes), and the call was
 * most of them: this is the single load SwdPin::read() would end up doing anyway.
 */
static inline LN_ALWAYS_INLINE bool sdiReadPad()
{
    return rSWDIO->_fast.read();
}

/**
 * @brief Sample the 32 response cells that follow a read header, MSB first.
 *
 * Per cell (sdi.pio's rx_loop): wait for the boundary, pull the wire low for one
 * read clock, release it and turn the shifter around, then sample at the cell's
 * sample tick. The boundary comes from the update flag (waitCellBoundary()), so
 * an overrun cell is taken late instead of dropped, and both the LOW and the
 * sample are measured from the operations that make them, so a late boundary
 * shifts the cell instead of distorting it: whatever the target sees is always
 * one LOW per cell, 224 ns or more wide, with the sample the same distance
 * behind it as in the RP2040 timing (616 - 224 ns).
 *
 * The first cell is the one right after the last header cell, and its boundary
 * is waited for the way the header waits (waitCellStart()): the header's own
 * cells leave most of a cell of slack, so that wait cannot be late, and the flag
 * it leaves behind is consumed there so the loop below sees exactly one per cell.
 */
/**
 * @brief Sample the 32 response cells the carrier is clocking out.
 *
 * The cells are the timer's now: the LOW, the release, and the two shifter
 * turn-arounds that have to happen *with* the release (the DIR channels above).
 * What is left for the CPU is the part it is fast enough for - wait for the
 * boundary (the update flag, the same latch a CPU timed cell used) and read the
 * pad at the sample tick - i.e. ~3 bus accesses per cell against the ~10 a hand
 * made cell costs, which is what makes the loop fit inside the 24 ticks between
 * the sample and the next boundary.
 *
 * The sample tick is absolute, so a late boundary moves the sample *later*, never
 * into the next cell: the target holds its bit until the next falling edge
 * (sdi.txt §2: data windows are (T,2T) LOW and (T,8T) HIGH), so anywhere between
 * 500 ns and the end of the cell reads the same bit. Without that the boundary
 * wait would have to be exact, which is what the previous CPU timed design tried
 * and could not do.
 */
static uint32_t sdiSampleWord()
{
    uint32_t word = 0;

    /* The header's cells are the carrier's too and they leave nothing to do per
     * cell: the DIR stays "probe" there (a write-like phase, §2.2's phase table),
     * and the DIR word sequence for the whole frame - header, response and stop
     * cell - was armed before the clock started. */
    for (int i = 0; i < SDI_HEADER_BITS; i++)
    {
        if (sdiTimer->waitCellBoundary())
            sdiRxLateCells++;
    }

    for (int i = 0; i < SDI_WORD_BITS; i++)
    {
        // cell i's boundary is the one the header's loop (i == 0) or the previous
        // iteration (i > 0) has just taken
        if (i && sdiTimer->waitCellBoundary())
            sdiRxLateCells++;
        sdiTimer->waitTick(sdiTimer->sampleTick());
        word = (word << 1) | (sdiReadPad() ? 1U : 0U);
    }
    return word;
}


// ---------------------------------------------------------------------------
// Frame level: the SDI transport (same wire format as sdi_write / sdi_read in
// bmp_sdiTap_rp2040.cpp).
// ---------------------------------------------------------------------------
/**
 * @brief Send one DM write: the nine header cells and the 32 payload cells as
 *        *one* contiguous packet, then idle high.
 *
 * The packet is a single 41-cell unit (§2.1: start bit, 7 address bits, R/W, 32
 * data bits): a HIGH of 10 T or more *is* a stop bit (§2.2), so splitting the
 * header and the payload into two frames - which is what a gap between the two
 * sdiSendFrame() calls amounts to - ends the packet after the header and the
 * payload is then parsed as a packet of its own. That is only accidentally
 * right for a payload whose MSB is 0, where it forms a §2.1 *bypass packet*
 * ("1 bit start bit, fixed as data 0 ... read/write bits and register addresses
 * are the same as the most recent New Packet transfer"): 0x5AA50400 goes
 * through that way, while a payload whose MSB is 1 (dmcontrol = 0x80000001, any
 * value with bit 31 set) becomes a bogus new packet - start bit 1, address
 * bits [30:24], R/W = bit 23 - and the write is silently dropped. sdi.pio is
 * continuous across the two words for the same reason: its second `pull block`
 * already has the payload in the FIFO by the time the header's nine cells are
 * out, so the state machine never stalls between them.
 *
 * The 55 us that follow are the §2.2 stop/idle (>= 10 T) before the next write.
 */
static void sdiWriteFrame(const uint8_t adr, const uint32_t data)
{
    uint16_t duties[SDI_HEADER_BITS + SDI_WORD_BITS + 1]; // 41 cells + the stop cell
    int cells = sdiBuildHeader(duties, adr, SDI_WRITE_FLAG);

    cells += sdiBuildWord(duties + cells, data);
    sdiSendFrame(duties, cells);
    lnDelayUs(END_OF_WRITE_DELAY);
    /* One line per write, so the *shape* of the packet is checkable without a
     * scope: "one packet" is exactly what the two-frame write of §12 could not
     * print, and a firmware whose console has no such line is a firmware whose
     * write path is not this one. Reported after the §2.2 stop delay, so it
     * cannot shorten the write's idle. Single Logger call on purpose: the
     * output path drains one shared buffer, so two back-to-back calls can drop
     * the first line. */
    Logger("SDI : write 0x%02x = 0x%x : one packet, %d cells\n", (unsigned)adr, (unsigned)data, cells);
}

/**
 * @brief Send one DM read: the nine header cells and the 32 response cells as
 *        one carrier frame, sampling the response while it runs.
 *
 * Structurally the same frame a write uses - one DMA packet, one compare event
 * per cell, CHCV = the cell's LOW time - with two differences, and they are what
 * makes a read possible at all:
 *
 *  - the pad goes to the channel in *open drain* (sdiPinToTimerOpenDrain()), so
 *    the HIGHs are a release: the target drives the wire for the second half of
 *    every response cell and the probe reads it there,
 *  - the level shifter's turn-around comes from the timer's own compare events
 *    (the two DIR channels), so the release and the direction change are the same
 *    instant instead of two CPU stores apart.
 *
 * The header's duties are its nine bits, every response cell's is LOW1: a read
 * clock carries no data of its own (§2.2 - the probe's LOW is the clock and the
 * target's level during the HIGH is the bit).
 *
 * Interrupts stay masked, as they were for the CPU timed frame: the CPU only
 * samples now, but an ISR inside a cell would still push a sample past the
 * boundary, and the scan runs reads back to back. The Logger call stays outside
 * the masked section.
 */
static uint32_t sdiReadFrame(const uint8_t adr)
{
    uint16_t duties[SDI_HEADER_BITS + SDI_WORD_BITS + 1]; // 41 cells + the stop cell
    uint32_t word;
    int cells;

    sdiRxLateCells = 0;
    lnNoInterrupt();

    cells = sdiBuildHeader(duties, adr, SDI_READ_FLAG);
    for (int i = 0; i < SDI_WORD_BITS; i++)
        duties[cells + i] = (uint16_t)sdiTimer->low1();

    sdiPinToTimerOpenDrain();
    sdiTimer->armDmaFrame(duties, cells + SDI_WORD_BITS);
    sdiTimer->armDirFrame();
    sdiTimer->releaseCells();
    word = sdiSampleWord();
    sdiTimer->waitSentinelCell(); // the stop cell: the wire is high from here on
    sdiTimer->stopDmaFrame();
    sdiTimer->disarmDirFrame();
    sdiPinToOpenDrain();
    lnInterrupts();

    /* Reported outside the masked section, and only the first time it happens.
     * The timer makes the cells either way, so this is a late *sample*, not a
     * wrong clock: worth one line when it happens - it means the CPU is too slow
     * for the cells and a response bit may have been read late - and silence when
     * it does not. Per frame it cannot print: the scan runs reads back to back
     * and a Logger call is longer than the read it would report. */
    if (sdiRxLateCells && !sdiRxLateReported)
    {
        sdiRxLateReported = true;
        Logger("SDI : read 0x%02x : %u of %u boundaries taken late (the timer makes the cells; only the sample is late)\n",
               (unsigned)adr, (unsigned)sdiRxLateCells, (unsigned)(SDI_HEADER_BITS + SDI_WORD_BITS));
    }

    rSWDIO->_fast.on();    // released...
    rSWDIO->_fastdir.on(); // ...and DIR back to the probe: the SWD idle state
    lnDelayUs(INTER_WORD_DELAY);
    return word;
}

// ---------------------------------------------------------------------------
// Pin mode side: ownership of PB8/PC3 for the duration of an SDI session. Called
// by bmp_gpio_pinmode() in bmp_tap_ln.cpp, the LN platform file that knows every
// mode (mirroring bmp_tap_rp2040.cpp on the RP2040 side).
// ---------------------------------------------------------------------------
/**
 * @brief Enter SDI mode: build the cell engine and park PB8 released.
 *
 * PB8 leaves the tap in open drain and released, with the shifter pointing at
 * the probe, which is the state every frame starts and ends in.
 */
void sdi_pinmode_enter()
{
    if (!rSWDIO)
        return;
    if (!sdiTimer)
    {
        sdiTimer = new SdiTimer(SDI_DATA_PIN);
        sdiTimer->configure();
        sdiTimer->logTicks();
    }
    sdiRxLateReported = false; // one late-cell report per SDI session
    if (!sdiMode)
    {
        rSWDIO->_fast.on();    // released
        rSWDIO->_fastdir.on(); // DIR = probe
        lnPinMode(SDI_DATA_PIN, lnOUTPUT_OPEN_DRAIN, 1);
        Logger("SDI : SDI mode on pin %d\n", (int)SDI_DATA_PIN);
    }
    sdiMode = true;
}

/**
 * @brief Leave SDI mode: stop the clock and give the pad back released.
 *
 * PB8/PC3 are left in the state the SWD/RVSWD taps start from (released open
 * drain, direction at the probe, PB8 forced high by SwdPin::on()), so the next
 * swdptap_init()/rvswd_scan() takes over without a fight on the wire.
 */
void sdi_pinmode_leave()
{
    if (!sdiMode)
        return;
    sdiMode = false;
    if (sdiTimer)
        sdiTimer->stopClock();
    if (rSWDIO)
    {
        rSWDIO->_fast.on();    // released
        rSWDIO->_fastdir.on(); // DIR = probe
        lnPinMode(SDI_DATA_PIN, lnOUTPUT_OPEN_DRAIN, 1);
    }
    Logger("SDI : leaving SDI mode\n");
}

// EOF