
set(LNBMP_VERSION_MAJOR "0")
set(LNBMP_VERSION_MINOR "600")

macro(GEN_VERSION_FILE)
  # Gen version for swindle ____________________________
  execute_process(
    COMMAND git log -1 --format=%h
    WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}
    OUTPUT_VARIABLE GIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE)

  set(VERSION_FILE ${CMAKE_BINARY_DIR}/lnBMP_version.h)
  file(WRITE ${VERSION_FILE} "// Generated by cmake!\n")
  file(APPEND ${VERSION_FILE} "#define LN_BMP_VERSION  \"${LNBMP_VERSION_MAJOR}.${LNBMP_VERSION_MINOR}\"\n")
  file(APPEND ${VERSION_FILE} "#define LN_BMP_GEN_DATE \"${timestamp}\"\n")
  file(APPEND ${VERSION_FILE} "#define LN_BMP_GIT_HASH \"${GIT_HASH}\"\n")

  # Gen version for bmp itself ____________________________
  set(BMP_VERSION_FILE ${CMAKE_BINARY_DIR}/version.h)
  if(NOT EXISTS "${BMP_VERSION_FILE}")
    execute_process(
      COMMAND git log -1 --format=%h
      WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}
      OUTPUT_VARIABLE BMP_GIT_HASH
      OUTPUT_STRIP_TRAILING_WHITESPACE)
    file(WRITE ${BMP_VERSION_FILE} "// Generated by cmake!\n")
    file(APPEND ${BMP_VERSION_FILE} "#define FIRMWARE_VERSION  \"${BMP_GIT_HASH}\"\n")
  endif()

endmacro()
