

SET(LNBMP_VERSION_MAJOR "0")
SET(LNBMP_VERSION_MINOR "600")

MACRO(GEN_VERSION_FILE)
  # Gen version for swindle
  #____________________________
  execute_process(
    COMMAND git log -1 --format=%h
    WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}
    OUTPUT_VARIABLE GIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE
    )

  SET(VERSION_FILE ${CMAKE_BINARY_DIR}/lnBMP_version.h)
  FILE(WRITE ${VERSION_FILE} "// Generated by cmake!\n")
  FILE(APPEND  ${VERSION_FILE} "#define LN_BMP_VERSION  \"${LNBMP_VERSION_MAJOR}.${LNBMP_VERSION_MINOR}\"\n")
  FILE(APPEND  ${VERSION_FILE} "#define LN_BMP_GEN_DATE \"${timestamp}\"\n")
  FILE(APPEND  ${VERSION_FILE} "#define LN_BMP_GIT_HASH \"${GIT_HASH}\"\n")

  #Gen version for bmp itself
  #____________________________
  SET(BMP_VERSION_FILE ${CMAKE_BINARY_DIR}/version.h)
  IF(NOT EXISTS "${BMP_VERSION_FILE}")
    execute_process(
      COMMAND git log -1 --format=%h
      WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}
      OUTPUT_VARIABLE BMP_GIT_HASH
      OUTPUT_STRIP_TRAILING_WHITESPACE
      )
    FILE(WRITE ${BMP_VERSION_FILE} "// Generated by cmake!\n")
    FILE(APPEND  ${BMP_VERSION_FILE} "#define FIRMWARE_VERSION  \"${BMP_GIT_HASH}\"\n")
  ENDIF()

ENDMACRO()


