/*
 */
/**
 * This is similar to the non rp2040 except we switch to bit banging dynamically
 *
 */

// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //
#include "lnGPIO.h"
#include "ln_rp_pio.h"
#include "stdint.h"
#include "hardware/gpio.h"
#define PICO_NO_HARDWARE 1
#include "bmp_pio_sdi.h"

#define PIN_TO_USE GPIO13
#define PIN_RESET GPIO10
#define SDIO_SPEED (16000000)

#define STEP 1

#define SDI_WRITE 0x80
#define SDI_READ 0x00

#define DMCONTROL 0x10
#define DMSTATUS 0x11

// 9-bit Header Structure (Start bit + 7 Address bits + 1 R/W bit)
#define SDI_START_BIT 1

static inline uint32_t make_sdi_header(uint8_t tgt, uint8_t mode)
{
    return (SDI_START_BIT << 8) | (tgt << 1) | mode;
}

static uint32_t sdi_read(rpPIO_SM *xsm, const uint8_t adr)
{
    // Word 1: Mode=0 (bit 31), Header (bits 30 down to 22)
    uint32_t header9 = make_sdi_header(adr, 0);
    uint32_t w = (0 << 31) | (header9 << 22);
    xsm->write(1, &w);

    xsm->read(1, &w);
    lnDelayUs(2);
    return w;
}

static void sdi_write(rpPIO_SM *xsm, const uint8_t adr, const uint32_t data)
{
    // Word 1: Mode=1 (bit 31), Header (bits 30 down to 22)
    uint32_t header9 = make_sdi_header(adr, 1);
    uint32_t w1 = (1U << 31) | (header9 << 22);
    xsm->write(1, &w1);

    // Word 2: The exact 32-bit payload
    xsm->write(1, &data);
    lnDelayUs(2);
}
static void sdi_reset(rpPIO_SM *xsm, uint32_t ms)
{
    xsm->setPinDir(PIN_TO_USE, true); // Drive LOW (assumes output value is 0)
    lnDelayMs(ms);
    xsm->setPinDir(PIN_TO_USE, false); // Release to float HIGH
                                       //
    sdi_write(xsm, 0x7e, 0x5AA50400);  // address 0x7E
    lnDelayMs(2);
    sdi_write(xsm, 0x7d, 0x5AA50400); // address 0x7D
    lnDelayMs(2);
}
#if 0
void runPio()
{

    lnDigitalWrite(PIN_RESET, 0); // it is inverted
    lnPinMode(PIN_RESET, lnOUTPUT);

    lnPin pin = PIN_TO_USE;
    rpPIO xpio(0);
    rpPIO_SM *xsm = xpio.getSm(0);

    lnPinModePIO((lnPin)pin, 0, true); // PIO0+pullup

    rpPIO_pinConfig pinConfig;
    pinConfig.sets.pinNb = 1;
    pinConfig.sets.startPin = pin;
    pinConfig.outputs.pinNb = 1;
    pinConfig.outputs.startPin = pin;
    pinConfig.inputs.pinNb = 1;
    pinConfig.inputs.startPin = pin;

    xsm->setSpeed(SDIO_SPEED);
    xsm->setBitOrder(false, false); // MSB-first for WCH SDI protocol!
    xsm->uploadCode(sizeof(sdi_program_instructions) / 2, sdi_program_instructions, sdi_wrap_target, sdi_wrap);
    xsm->configure(pinConfig);

    // Explicitly set the PIO pin output level to 0.
    // This is required for the pseudo open-drain logic:
    // When pindirs=1, it drives the 0. When pindirs=0, it floats.
    xsm->setPinsValue(0);
    xsm->setPinDir(pin, false);

    xsm->execute();

    lnDigitalWrite(PIN_RESET, 1); // it is inverted
    lnDelayMs(20);
    lnDigitalWrite(PIN_RESET, 0); // it is inverted
    sdi_reset(xsm, 20);           // Hold SDI line low to reset target

    while (1)
    {
#if 0

        sdi_write(xsm, DMSTATUS, 0x5555U);
#else
        lnDelayMs(5);
        uint32_t status = sdi_read(xsm, DMSTATUS);
#endif
        // Logger("Status = 0x%x\n", status);
    }
}

//-
bool LN_FAST_CODE rv_dm_write(uint32_t adr, uint32_t val);
bool LN_FAST_CODE rv_dm_read(uint32_t adr, uint32_t *output);
#endif
