// Auto-generated by generate_rpc.py — DO NOT EDIT
// Source: rpc_protocol.toml

#![allow(dead_code)]
#![allow(non_upper_case_globals)]
#![allow(unused_variables)]
#![allow(unused_imports)]

// ── Packet class bytes ──
pub const RPC_GEN_PACKET: u8 = b'G';
pub const RPC_SWDP_PACKET: u8 = b'S';
pub const RPC_HL_PACKET: u8 = b'H';
pub const RPC_RV_PACKET: u8 = b'B';
pub const RPC_LNADIV_PACKET: u8 = b'L';
pub const RPC_ADIV5_PACKET: u8 = b'A';
pub const RPC_SWINDLE_PACKET: u8 = b'Z';
pub const RPC_JTAG_PACKET: u8 = b'J';
pub const RPC_SPI_PACKET: u8 = b's';

// ── Command bytes ──
pub const RPC_GEN_START: u8 = b'A';
pub const RPC_GEN_VOLTAGE: u8 = b'V';
pub const RPC_GEN_NRST_SET: u8 = b'Z';
pub const RPC_GEN_NRST_GET: u8 = b'z';
pub const RPC_GEN_TARGET_CLK_OE: u8 = b'E';
pub const RPC_GEN_FREQ_SET: u8 = b'F';
pub const RPC_GEN_FREQ_GET: u8 = b'f';
pub const RPC_GEN_PWR_SET: u8 = b'P';
pub const RPC_GEN_PWR_GET: u8 = b'p';
pub const RPC_GEN_GPIO_RESET: u8 = b'R';
pub const RPC_SWDP_INIT: u8 = b'S';
pub const RPC_HL_CHECK: u8 = b'C';
pub const RPC_HL_ACCEL: u8 = b'A';
pub const RPC_RV_RESET: u8 = b'S';
pub const RPC_RV_DM_READ: u8 = b'r';
pub const RPC_RV_DM_WRITE: u8 = b'w';
pub const RPC_LNADIV_WRITE: u8 = b'W';
pub const RPC_LNADIV_READ: u8 = b'R';
pub const RPC_LNADIV_RAW_WRITE: u8 = b'A';
pub const RPC_LNADIV_LOWLEVEL: u8 = b'B';
pub const RPC_ADIV5_RAW_ACCESS_V3: u8 = b'R';
pub const RPC_ADIV5_DP_READ: u8 = b'd';
pub const RPC_ADIV5_AP_READ: u8 = b'a';
pub const RPC_ADIV5_AP_WRITE: u8 = b'A';
pub const RPC_ADIV5_MEM_READ: u8 = b'm';
pub const RPC_ADIV5_MEM_WRITE: u8 = b'M';
pub const RPC_SWINDLE_CRC32: u8 = b'C';
pub const RPC_SWINDLE_GET_FQ: u8 = b'G';
pub const RPC_SWINDLE_SET_FQ: u8 = b'S';

// ── Response codes ──
pub const RPC_RESP_OK: u8 = b'K';
pub const RPC_RESP_PARERR: u8 = b'P';
pub const RPC_RESP_ERR: u8 = b'E';
pub const RPC_RESP_NOTSUP: u8 = b'N';
pub const RPC_REMOTE_RESP: u8 = b'&';

// ── Error codes ──
pub const RPC_ERROR_UNRECOGNISED: u8 = 1;
pub const RPC_ERROR_WRONGLEN: u8 = 2;
pub const RPC_ERROR_FAULT: u8 = 3;
pub const RPC_ERROR_EXCEPTION: u8 = 4;

// ── Framing ──
pub const RPC_END: u8 = b'#';
