// Auto-generated by generate_rpc.py — DO NOT EDIT
// Source: rpc_protocol.toml

#![allow(dead_code)]
#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(unused_imports)]

use crate::rpc_common_generated::*;
use crate::rpc_target::rpc_parser::rpc_parameter_parser;
use crate::rpc_target::*;
use crate::rpc_target::rpc_reply::*;
use crate::bmp;
use crate::parsing_util;
use crate::encoder::*;

crate::setup_log!(false);
crate::gdb_print_init!();

// ── Top-level dispatch ──
#[unsafe(no_mangle)]
pub fn rpc_dispatch(input: &[u8]) -> bool {
    if input.len() < 2 {
        bmplog!("**short rpc\n");
        return false;
    }
    let mut parser = rpc_parameter_parser::new(input);
    match parser.next_cmd() {
        RPC_GEN_PACKET => rpc_gen_impl::dispatch(&mut parser),
        RPC_SWDP_PACKET => rpc_swdp_impl::dispatch(&mut parser),
        RPC_HL_PACKET => rpc_hl_impl::dispatch(&mut parser),
        RPC_RV_PACKET => rpc_rv_impl::dispatch(&mut parser),
        RPC_LNADIV_PACKET => rpc_lnadiv_impl::dispatch(&mut parser),
        RPC_ADIV5_PACKET => rpc_adiv5_impl::dispatch(&mut parser),
        RPC_SWINDLE_PACKET => rpc_swindle_impl::dispatch(&mut parser),
        _ => {
            bmplog!("wrong RPC header\n");
            false
        }
    }
}

// ── GEN dispatch ──
pub mod rpc_gen_impl {
    use super::*;

    pub fn dispatch(parser: &mut rpc_parameter_parser) -> bool {
        match parser.next_cmd() {
            RPC_GEN_START => cmd_start(parser),
            RPC_GEN_VOLTAGE => cmd_voltage(parser),
            RPC_GEN_NRST_SET => cmd_nrst_set(parser),
            RPC_GEN_NRST_GET => cmd_nrst_get(parser),
            RPC_GEN_TARGET_CLK_OE => cmd_target_clk_oe(parser),
            RPC_GEN_FREQ_SET => cmd_freq_set(parser),
            RPC_GEN_FREQ_GET => cmd_freq_get(parser),
            RPC_GEN_PWR_SET => cmd_pwr_set(parser),
            RPC_GEN_PWR_GET => cmd_pwr_get(parser),
            _ => {
                bmplog!("unknown command in {} packet\n", stringify!(GEN));
                false
            }
        }
    }

    fn cmd_start(parser: &mut rpc_parameter_parser) -> bool {
        let s = crate::rpc_target_impl::rpc_gen_impl::start();
        rpc_reply_string(s);
        true
    }

    fn cmd_voltage(parser: &mut rpc_parameter_parser) -> bool {
        let s = crate::rpc_target_impl::rpc_gen_impl::voltage();
        rpc_reply_string(s);
        true
    }

    fn cmd_nrst_set(parser: &mut rpc_parameter_parser) -> bool {
        let assert = parser.next_cmd() != b'0';
        crate::rpc_target_impl::rpc_gen_impl::nrst_set(assert);
        rpc_reply_encoder::new().end();
        true
    }

    fn cmd_nrst_get(parser: &mut rpc_parameter_parser) -> bool {
        let value = crate::rpc_target_impl::rpc_gen_impl::nrst_get();
        rpc_reply_ok(value as u8);
        true
    }

    fn cmd_target_clk_oe(parser: &mut rpc_parameter_parser) -> bool {
        let enable = parser.next_cmd() != b'0';
        crate::rpc_target_impl::rpc_gen_impl::target_clk_oe(enable);
        rpc_reply_encoder::new().end();
        true
    }

    fn cmd_freq_set(parser: &mut rpc_parameter_parser) -> bool {
        let freq_khz = parser.next_u32();
        crate::rpc_target_impl::rpc_gen_impl::freq_set(freq_khz);
        rpc_reply_encoder::new().end();
        true
    }

    fn cmd_freq_get(parser: &mut rpc_parameter_parser) -> bool {
        let value = crate::rpc_target_impl::rpc_gen_impl::freq_get();
        rpc_reply32_le_ok(value);
        true
    }

    fn cmd_pwr_set(parser: &mut rpc_parameter_parser) -> bool {
        let enabled = parser.next_cmd() != b'0';
        crate::rpc_target_impl::rpc_gen_impl::pwr_set(enabled);
        rpc_reply_encoder::new().end();
        true
    }

    fn cmd_pwr_get(parser: &mut rpc_parameter_parser) -> bool {
        let value = crate::rpc_target_impl::rpc_gen_impl::pwr_get();
        rpc_reply_ok(value as u8);
        true
    }

}

// ── SWDP dispatch ──
pub mod rpc_swdp_impl {
    use super::*;

    pub fn dispatch(parser: &mut rpc_parameter_parser) -> bool {
        match parser.next_cmd() {
            RPC_SWDP_INIT => cmd_init(parser),
            _ => {
                bmplog!("unknown command in {} packet\n", stringify!(SWDP));
                false
            }
        }
    }

    fn cmd_init(parser: &mut rpc_parameter_parser) -> bool {
        crate::rpc_target_impl::rpc_swdp_impl::init();
        rpc_reply_encoder::new().end();
        true
    }

}

// ── HL dispatch ──
pub mod rpc_hl_impl {
    use super::*;

    pub fn dispatch(parser: &mut rpc_parameter_parser) -> bool {
        match parser.next_cmd() {
            RPC_HL_CHECK => cmd_check(parser),
            RPC_HL_ACCEL => cmd_accel(parser),
            _ => {
                bmplog!("unknown command in {} packet\n", stringify!(HL));
                false
            }
        }
    }

    fn cmd_check(parser: &mut rpc_parameter_parser) -> bool {
        let value = crate::rpc_target_impl::rpc_hl_impl::check();
        rpc_reply_ok(value as u8);
        true
    }

    fn cmd_accel(parser: &mut rpc_parameter_parser) -> bool {
        let value = crate::rpc_target_impl::rpc_hl_impl::accel();
        rpc_reply_ok(value as u8);
        true
    }

}

// ── RV dispatch ──
pub mod rpc_rv_impl {
    use super::*;

    pub fn dispatch(parser: &mut rpc_parameter_parser) -> bool {
        match parser.next_cmd() {
            RPC_RV_RESET => cmd_reset(parser),
            RPC_RV_DM_READ => cmd_dm_read(parser),
            RPC_RV_DM_WRITE => cmd_dm_write(parser),
            _ => {
                bmplog!("unknown command in {} packet\n", stringify!(RV));
                false
            }
        }
    }

    fn cmd_reset(parser: &mut rpc_parameter_parser) -> bool {
        let (ok, value) = crate::rpc_target_impl::rpc_rv_impl::reset();
        rpc_reply_bool_32le(ok, value);
        true
    }

    fn cmd_dm_read(parser: &mut rpc_parameter_parser) -> bool {
        let address = parser.next_u8();
        let (ok, value) = crate::rpc_target_impl::rpc_rv_impl::dm_read(address);
        rpc_reply_bool_32le(ok, value);
        true
    }

    fn cmd_dm_write(parser: &mut rpc_parameter_parser) -> bool {
        let address = parser.next_u8();
        let value = parser.next_u32();
        let (ok, value) = crate::rpc_target_impl::rpc_rv_impl::dm_write(address, value);
        rpc_reply_bool_32le(ok, value);
        true
    }

}

// ── LNADIV dispatch ──
pub mod rpc_lnadiv_impl {
    use super::*;

    pub fn dispatch(parser: &mut rpc_parameter_parser) -> bool {
        match parser.next_cmd() {
            RPC_LNADIV_WRITE => cmd_write(parser),
            RPC_LNADIV_READ => cmd_read(parser),
            RPC_LNADIV_RAW_WRITE => cmd_raw_write(parser),
            RPC_LNADIV_LOWLEVEL => cmd_lowlevel(parser),
            _ => {
                bmplog!("unknown command in {} packet\n", stringify!(LNADIV));
                false
            }
        }
    }

    fn cmd_write(parser: &mut rpc_parameter_parser) -> bool {
        let address = parser.next_u16();
        let data = parser.next_u32();
        let (ok, value) = crate::rpc_target_impl::rpc_lnadiv_impl::write(address, data);
        rpc_reply_bool_32le(ok, value);
        true
    }

    fn cmd_read(parser: &mut rpc_parameter_parser) -> bool {
        let address = parser.next_u16();
        let (ok, value) = crate::rpc_target_impl::rpc_lnadiv_impl::read(address);
        rpc_reply_bool_32le(ok, value);
        true
    }

    fn cmd_raw_write(parser: &mut rpc_parameter_parser) -> bool {
        let tick_count = parser.next_u32();
        let value = parser.next_u32();
        let (ok, value) = crate::rpc_target_impl::rpc_lnadiv_impl::raw_write(tick_count, value);
        rpc_reply_bool_32le(ok, value);
        true
    }

    fn cmd_lowlevel(parser: &mut rpc_parameter_parser) -> bool {
        let rnw = parser.next_u8();
        let address = parser.next_u16();
        let value = parser.next_u32();
        let (response, fault) = crate::rpc_target_impl::rpc_lnadiv_impl::lowlevel(rnw, address, value);
        let mut reply = rpc_reply_encoder::new();
        reply.add_u32_le_wrapped(response);
        reply.add_u32_le_wrapped(fault);
        reply.end();
        true
    }

}

// ── ADIV5 dispatch ──
pub mod rpc_adiv5_impl {
    use super::*;

    pub fn dispatch(parser: &mut rpc_parameter_parser) -> bool {
        match parser.next_cmd() {
            RPC_ADIV5_RAW_ACCESS_V3 => cmd_raw_access_v3(parser),
            RPC_ADIV5_DP_READ => cmd_dp_read(parser),
            RPC_ADIV5_AP_READ => cmd_ap_read(parser),
            RPC_ADIV5_AP_WRITE => cmd_ap_write(parser),
            RPC_ADIV5_MEM_READ => cmd_mem_read(parser),
            RPC_ADIV5_MEM_WRITE => cmd_mem_write(parser),
            _ => {
                bmplog!("unknown command in {} packet\n", stringify!(ADIV5));
                false
            }
        }
    }

    fn cmd_raw_access_v3(parser: &mut rpc_parameter_parser) -> bool {
        let device_index = parser.next_u8();
        let ap_selection = parser.next_u8();
        let address = parser.next_u16_be();
        let value = parser.next_u32_be();
        let (outvalue, fault) = crate::rpc_target_impl::rpc_adiv5_impl::raw_access_v3(device_index, ap_selection, address, value);
        if fault != 0 {
            rpc_reply_error(RPC_ERROR_FAULT);
            return true;
        }
        let mut reply = rpc_reply_encoder::new();
        reply.add_u32_le_wrapped(outvalue);
        reply.add_u32_le_wrapped(fault);
        reply.end();
        true
    }

    fn cmd_dp_read(parser: &mut rpc_parameter_parser) -> bool {
        let device_index = parser.next_u8();
        let ap_selection = parser.next_u8();
        let address = parser.next_u32_be();
        let (fault, value) = crate::rpc_target_impl::rpc_adiv5_impl::dp_read(device_index, ap_selection, address);
        reply_adiv5_32(fault, value);
        true
    }

    fn cmd_ap_read(parser: &mut rpc_parameter_parser) -> bool {
        let device_index = parser.next_u8();
        let ap_selection = parser.next_u8();
        let address = parser.next_u16_be();
        let (fault, value) = crate::rpc_target_impl::rpc_adiv5_impl::ap_read(device_index, ap_selection, address);
        reply_adiv5_32(fault, value);
        true
    }

    fn cmd_ap_write(parser: &mut rpc_parameter_parser) -> bool {
        let device_index = parser.next_u8();
        let ap_selection = parser.next_u8();
        let address = parser.next_u16_be();
        let value = parser.next_u32_be();
        let (fault, value) = crate::rpc_target_impl::rpc_adiv5_impl::ap_write(device_index, ap_selection, address, value);
        reply_adiv5_32(fault, value);
        true
    }

    fn cmd_mem_read(parser: &mut rpc_parameter_parser) -> bool {
        let device_index = parser.next_u8();
        let ap_selection = parser.next_u8();
        let csw = parser.next_u32_be();
        let address = parser.next_u32_be();
        let length = parser.next_u32_be();
        let buffer = crate::rpc_target::rpc_reply::get_temp_buffer();
        let (fault, len) = crate::rpc_target_impl::rpc_adiv5_impl::mem_read(device_index, ap_selection, csw, address, length, buffer);
        if fault != 0 {
            rpc_reply_error(fault as u8);
            return true;
        }
        rpc_reply_hex_string(RPC_RESP_OK, &buffer[..len]);
        true
    }

    fn cmd_mem_write(parser: &mut rpc_parameter_parser) -> bool {
        let device_index = parser.next_u8();
        let ap_selection = parser.next_u8();
        let csw = parser.next_u32_be();
        let align = parser.next_u8();
        let address = parser.next_u32_be();
        let length = parser.next_u32_be();
        let data = parser.end();
        let (fault, value) = crate::rpc_target_impl::rpc_adiv5_impl::mem_write(device_index, ap_selection, csw, align, address, length, data);
        reply_adiv5_32(fault, value);
        true
    }

}

// ── SWINDLE dispatch ──
pub mod rpc_swindle_impl {
    use super::*;

    pub fn dispatch(parser: &mut rpc_parameter_parser) -> bool {
        match parser.next_cmd() {
            RPC_SWINDLE_CRC32 => cmd_crc32(parser),
            RPC_SWINDLE_GET_FQ => cmd_get_fq(parser),
            RPC_SWINDLE_SET_FQ => cmd_set_fq(parser),
            _ => {
                bmplog!("unknown command in {} packet\n", stringify!(SWINDLE));
                false
            }
        }
    }

    fn cmd_crc32(parser: &mut rpc_parameter_parser) -> bool {
        let address = parser.next_u32();
        let length = parser.next_u32();
        let (ok, value) = crate::rpc_target_impl::rpc_swindle_impl::crc32(address, length);
        rpc_reply_bool_32le(ok, value);
        true
    }

    fn cmd_get_fq(parser: &mut rpc_parameter_parser) -> bool {
        let (ok, value) = crate::rpc_target_impl::rpc_swindle_impl::get_fq();
        rpc_reply_bool_32le(ok, value);
        true
    }

    fn cmd_set_fq(parser: &mut rpc_parameter_parser) -> bool {
        let freq_hz = parser.next_u32();
        crate::rpc_target_impl::rpc_swindle_impl::set_fq(freq_hz);
        rpc_reply_encoder::new().end();
        true
    }

}

